!SESSION 2019-12-14 17:09:20.596 -----------------------------------------------
eclipse.buildId=4.8.0.I20180611-0500
java.version=1.8.0_144
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en_US
Framework arguments:  -product com.ti.ccstudio.branding.product
Command-line arguments:  -os win32 -ws win32 -arch x86_64 -product com.ti.ccstudio.branding.product

This is a continuation of log file C:\Users\Alan\Downloads\tirslk_max_1_00_00\.metadata\.bak_0.log
Created Time: 2019-12-15 16:30:47.895

!ENTRY com.ti.ccstudio.debug 4 0 2019-12-15 16:30:47.911
!MESSAGE An internal error was logged by 'com.ti.ccstudio.debug'.
!STACK 0
java.util.concurrent.ExecutionException: org.json.JSONException: Module Closed
	at java.util.concurrent.CompletableFuture.reportGet(Unknown Source)
	at java.util.concurrent.CompletableFuture.get(Unknown Source)
	at com.ti.ccstudio.debug.service.ApplicationService.getConnectedDebugProbes(ApplicationService.java:295)
	at com.ti.ccstudio.debug.service.ApplicationService.detectXDS110ConnectedProbes(ApplicationService.java:356)
	at com.ti.ccstudio.debug.service.ApplicationService.initDebugger(ApplicationService.java:418)
	at com.ti.ccstudio.debug.service.ApplicationService.access$0(ApplicationService.java:408)
	at com.ti.ccstudio.debug.service.ApplicationService$ThreadContextCache.retrieve(ApplicationService.java:136)
	at com.ti.ccstudio.debug.dsf.extensions.concurrent.DataCache.wait(DataCache.java:59)
	at com.ti.ccstudio.debug.service.ApplicationService.getCpuBeingDebugged(ApplicationService.java:1057)
	at com.ti.ccstudio.debug.launch.CCSLaunchDelegate$2.execute(CCSLaunchDelegate.java:139)
	at org.eclipse.cdt.dsf.concurrent.Query.run(Query.java:177)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: org.json.JSONException: Module Closed
	at com.ti.cloudagent.communication.JSONInterface.call(JSONInterface.java:54)
	at com.ti.cloudagent.Agent.createModule(Agent.java:171)
	at com.ti.cloudagent.Agent.lambda$createSpecificModule$4(Agent.java:96)
	at java.util.concurrent.CompletableFuture.uniHandle(Unknown Source)
	at java.util.concurrent.CompletableFuture.uniHandleStage(Unknown Source)
	at java.util.concurrent.CompletableFuture.handle(Unknown Source)
	at com.ti.cloudagent.Agent.createSpecificModule(Agent.java:87)
	at com.ti.cloudagent.Agent.createDeviceDetector(Agent.java:76)
	... 16 more

!ENTRY com.ti.ccstudio.debug 4 0 2019-12-15 16:32:12.093
!MESSAGE An internal error was logged by 'com.ti.ccstudio.debug'.
!STACK 0
java.util.concurrent.ExecutionException: org.json.JSONException: Module Closed
	at java.util.concurrent.CompletableFuture.reportGet(Unknown Source)
	at java.util.concurrent.CompletableFuture.get(Unknown Source)
	at com.ti.ccstudio.debug.service.ApplicationService.getConnectedDebugProbes(ApplicationService.java:295)
	at com.ti.ccstudio.debug.service.ApplicationService.detectXDS110ConnectedProbes(ApplicationService.java:356)
	at com.ti.ccstudio.debug.service.ApplicationService.initDebugger(ApplicationService.java:418)
	at com.ti.ccstudio.debug.service.ApplicationService.access$0(ApplicationService.java:408)
	at com.ti.ccstudio.debug.service.ApplicationService$ThreadContextCache.retrieve(ApplicationService.java:136)
	at com.ti.ccstudio.debug.dsf.extensions.concurrent.DataCache.wait(DataCache.java:59)
	at com.ti.ccstudio.debug.service.ApplicationService.getCpuBeingDebugged(ApplicationService.java:1057)
	at com.ti.ccstudio.debug.launch.CCSLaunchDelegate$2.execute(CCSLaunchDelegate.java:139)
	at org.eclipse.cdt.dsf.concurrent.Query.run(Query.java:177)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: org.json.JSONException: Module Closed
	at com.ti.cloudagent.communication.JSONInterface.call(JSONInterface.java:54)
	at com.ti.cloudagent.Agent.createModule(Agent.java:171)
	at com.ti.cloudagent.Agent.lambda$createSpecificModule$4(Agent.java:96)
	at java.util.concurrent.CompletableFuture.uniHandle(Unknown Source)
	at java.util.concurrent.CompletableFuture.uniHandleStage(Unknown Source)
	at java.util.concurrent.CompletableFuture.handle(Unknown Source)
	at com.ti.cloudagent.Agent.createSpecificModule(Agent.java:87)
	at com.ti.cloudagent.Agent.createDeviceDetector(Agent.java:76)
	... 16 more

!ENTRY com.ti.ccstudio.debug 1 0 2019-12-15 16:33:26.052
!MESSAGE DS_ERROR: CORTEX_M4_0: JTAG Communication Error: (Error -613 @ 0x0) The target indicates that it is busy.  Either try the SWD request  again, or abort the transaction. (Emulation package 8.3.0.00003) 


!ENTRY com.ti.ccstudio.debug 1 0 2019-12-15 16:33:26.130
!MESSAGE DS_ERROR: CORTEX_M4_0: Failed to remove the debug state from the target before disconnecting.  There may still be breakpoint op-codes embedded in program memory.  It is recommended that you reset the emulator before you connect and reload your program before you continue debugging


!ENTRY com.ti.ccstudio.debug 4 0 2019-12-15 16:34:40.667
!MESSAGE An internal error was logged by 'com.ti.ccstudio.debug'.
!STACK 0
java.util.concurrent.ExecutionException: org.json.JSONException: Module Closed
	at java.util.concurrent.CompletableFuture.reportGet(Unknown Source)
	at java.util.concurrent.CompletableFuture.get(Unknown Source)
	at com.ti.ccstudio.debug.service.ApplicationService.getConnectedDebugProbes(ApplicationService.java:295)
	at com.ti.ccstudio.debug.service.ApplicationService.detectXDS110ConnectedProbes(ApplicationService.java:356)
	at com.ti.ccstudio.debug.service.ApplicationService.initDebugger(ApplicationService.java:418)
	at com.ti.ccstudio.debug.service.ApplicationService.access$0(ApplicationService.java:408)
	at com.ti.ccstudio.debug.service.ApplicationService$ThreadContextCache.retrieve(ApplicationService.java:136)
	at com.ti.ccstudio.debug.dsf.extensions.concurrent.DataCache.wait(DataCache.java:59)
	at com.ti.ccstudio.debug.service.ApplicationService.getCpuBeingDebugged(ApplicationService.java:1057)
	at com.ti.ccstudio.debug.launch.CCSLaunchDelegate$2.execute(CCSLaunchDelegate.java:139)
	at org.eclipse.cdt.dsf.concurrent.Query.run(Query.java:177)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: org.json.JSONException: Module Closed
	at com.ti.cloudagent.communication.JSONInterface.call(JSONInterface.java:54)
	at com.ti.cloudagent.Agent.createModule(Agent.java:171)
	at com.ti.cloudagent.Agent.lambda$createSpecificModule$4(Agent.java:96)
	at java.util.concurrent.CompletableFuture.uniHandle(Unknown Source)
	at java.util.concurrent.CompletableFuture.uniHandleStage(Unknown Source)
	at java.util.concurrent.CompletableFuture.handle(Unknown Source)
	at com.ti.cloudagent.Agent.createSpecificModule(Agent.java:87)
	at com.ti.cloudagent.Agent.createDeviceDetector(Agent.java:76)
	... 16 more

!ENTRY com.ti.ccstudio.debug 1 0 2019-12-15 16:34:40.950
!MESSAGE DS_ERROR: CS_DAP_0: Error connecting to the target: (Error -614 @ 0x0) The target indicates there is an error condition from a previous SWD  request. Clear the error the condition, and try the SWD request again. (Emulation package 8.3.0.00003) 


!ENTRY com.ti.ccstudio.debug 1 0 2019-12-15 16:34:41.143
!MESSAGE DS_ERROR: Error connecting to the target:
(Error -614 @ 0x0)
The target indicates there is an error condition from a previous SWD 
request. Clear the error the condition, and try the SWD request again.
(Emulation package 8.3.0.00003)


!ENTRY com.ti.ccstudio.debug 4 0 2019-12-15 16:39:41.435
!MESSAGE An internal error was logged by 'com.ti.ccstudio.debug'.
!STACK 0
java.util.concurrent.ExecutionException: org.json.JSONException: Module Closed
	at java.util.concurrent.CompletableFuture.reportGet(Unknown Source)
	at java.util.concurrent.CompletableFuture.get(Unknown Source)
	at com.ti.ccstudio.debug.service.ApplicationService.getConnectedDebugProbes(ApplicationService.java:295)
	at com.ti.ccstudio.debug.service.ApplicationService.detectXDS110ConnectedProbes(ApplicationService.java:356)
	at com.ti.ccstudio.debug.service.ApplicationService.initDebugger(ApplicationService.java:418)
	at com.ti.ccstudio.debug.service.ApplicationService.access$0(ApplicationService.java:408)
	at com.ti.ccstudio.debug.service.ApplicationService$ThreadContextCache.retrieve(ApplicationService.java:136)
	at com.ti.ccstudio.debug.dsf.extensions.concurrent.DataCache.wait(DataCache.java:59)
	at com.ti.ccstudio.debug.service.ApplicationService.getCpuBeingDebugged(ApplicationService.java:1057)
	at com.ti.ccstudio.debug.launch.CCSLaunchDelegate$2.execute(CCSLaunchDelegate.java:139)
	at org.eclipse.cdt.dsf.concurrent.Query.run(Query.java:177)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: org.json.JSONException: Module Closed
	at com.ti.cloudagent.communication.JSONInterface.call(JSONInterface.java:54)
	at com.ti.cloudagent.Agent.createModule(Agent.java:171)
	at com.ti.cloudagent.Agent.lambda$createSpecificModule$4(Agent.java:96)
	at java.util.concurrent.CompletableFuture.uniHandle(Unknown Source)
	at java.util.concurrent.CompletableFuture.uniHandleStage(Unknown Source)
	at java.util.concurrent.CompletableFuture.handle(Unknown Source)
	at com.ti.cloudagent.Agent.createSpecificModule(Agent.java:87)
	at com.ti.cloudagent.Agent.createDeviceDetector(Agent.java:76)
	... 16 more

!ENTRY com.ti.ccstudio.debug 4 0 2019-12-15 16:40:24.810
!MESSAGE An internal error was logged by 'com.ti.ccstudio.debug'.
!STACK 0
java.util.concurrent.ExecutionException: org.json.JSONException: Module Closed
	at java.util.concurrent.CompletableFuture.reportGet(Unknown Source)
	at java.util.concurrent.CompletableFuture.get(Unknown Source)
	at com.ti.ccstudio.debug.service.ApplicationService.getConnectedDebugProbes(ApplicationService.java:295)
	at com.ti.ccstudio.debug.service.ApplicationService.detectXDS110ConnectedProbes(ApplicationService.java:356)
	at com.ti.ccstudio.debug.service.ApplicationService.initDebugger(ApplicationService.java:418)
	at com.ti.ccstudio.debug.service.ApplicationService.access$0(ApplicationService.java:408)
	at com.ti.ccstudio.debug.service.ApplicationService$ThreadContextCache.retrieve(ApplicationService.java:136)
	at com.ti.ccstudio.debug.dsf.extensions.concurrent.DataCache.wait(DataCache.java:59)
	at com.ti.ccstudio.debug.service.ApplicationService.getCpuBeingDebugged(ApplicationService.java:1057)
	at com.ti.ccstudio.debug.launch.CCSLaunchDelegate$2.execute(CCSLaunchDelegate.java:139)
	at org.eclipse.cdt.dsf.concurrent.Query.run(Query.java:177)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: org.json.JSONException: Module Closed
	at com.ti.cloudagent.communication.JSONInterface.call(JSONInterface.java:54)
	at com.ti.cloudagent.Agent.createModule(Agent.java:171)
	at com.ti.cloudagent.Agent.lambda$createSpecificModule$4(Agent.java:96)
	at java.util.concurrent.CompletableFuture.uniHandle(Unknown Source)
	at java.util.concurrent.CompletableFuture.uniHandleStage(Unknown Source)
	at java.util.concurrent.CompletableFuture.handle(Unknown Source)
	at com.ti.cloudagent.Agent.createSpecificModule(Agent.java:87)
	at com.ti.cloudagent.Agent.createDeviceDetector(Agent.java:76)
	... 16 more

!ENTRY com.ti.ccstudio.debug 4 0 2019-12-15 16:41:26.865
!MESSAGE An internal error was logged by 'com.ti.ccstudio.debug'.
!STACK 0
java.util.concurrent.ExecutionException: org.json.JSONException: Module Closed
	at java.util.concurrent.CompletableFuture.reportGet(Unknown Source)
	at java.util.concurrent.CompletableFuture.get(Unknown Source)
	at com.ti.ccstudio.debug.service.ApplicationService.getConnectedDebugProbes(ApplicationService.java:295)
	at com.ti.ccstudio.debug.service.ApplicationService.detectXDS110ConnectedProbes(ApplicationService.java:356)
	at com.ti.ccstudio.debug.service.ApplicationService.initDebugger(ApplicationService.java:418)
	at com.ti.ccstudio.debug.service.ApplicationService.access$0(ApplicationService.java:408)
	at com.ti.ccstudio.debug.service.ApplicationService$ThreadContextCache.retrieve(ApplicationService.java:136)
	at com.ti.ccstudio.debug.dsf.extensions.concurrent.DataCache.wait(DataCache.java:59)
	at com.ti.ccstudio.debug.service.ApplicationService.getCpuBeingDebugged(ApplicationService.java:1057)
	at com.ti.ccstudio.debug.launch.CCSLaunchDelegate$2.execute(CCSLaunchDelegate.java:139)
	at org.eclipse.cdt.dsf.concurrent.Query.run(Query.java:177)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: org.json.JSONException: Module Closed
	at com.ti.cloudagent.communication.JSONInterface.call(JSONInterface.java:54)
	at com.ti.cloudagent.Agent.createModule(Agent.java:171)
	at com.ti.cloudagent.Agent.lambda$createSpecificModule$4(Agent.java:96)
	at java.util.concurrent.CompletableFuture.uniHandle(Unknown Source)
	at java.util.concurrent.CompletableFuture.uniHandleStage(Unknown Source)
	at java.util.concurrent.CompletableFuture.handle(Unknown Source)
	at com.ti.cloudagent.Agent.createSpecificModule(Agent.java:87)
	at com.ti.cloudagent.Agent.createDeviceDetector(Agent.java:76)
	... 16 more

!ENTRY com.ti.ccstudio.debug 4 0 2019-12-15 17:15:40.356
!MESSAGE An internal error was logged by 'com.ti.ccstudio.debug'.
!STACK 0
java.util.concurrent.ExecutionException: org.json.JSONException: Module Closed
	at java.util.concurrent.CompletableFuture.reportGet(Unknown Source)
	at java.util.concurrent.CompletableFuture.get(Unknown Source)
	at com.ti.ccstudio.debug.service.ApplicationService.getConnectedDebugProbes(ApplicationService.java:295)
	at com.ti.ccstudio.debug.service.ApplicationService.detectXDS110ConnectedProbes(ApplicationService.java:356)
	at com.ti.ccstudio.debug.service.ApplicationService.initDebugger(ApplicationService.java:418)
	at com.ti.ccstudio.debug.service.ApplicationService.access$0(ApplicationService.java:408)
	at com.ti.ccstudio.debug.service.ApplicationService$ThreadContextCache.retrieve(ApplicationService.java:136)
	at com.ti.ccstudio.debug.dsf.extensions.concurrent.DataCache.wait(DataCache.java:59)
	at com.ti.ccstudio.debug.service.ApplicationService.getCpuBeingDebugged(ApplicationService.java:1057)
	at com.ti.ccstudio.debug.launch.CCSLaunchDelegate$2.execute(CCSLaunchDelegate.java:139)
	at org.eclipse.cdt.dsf.concurrent.Query.run(Query.java:177)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: org.json.JSONException: Module Closed
	at com.ti.cloudagent.communication.JSONInterface.call(JSONInterface.java:54)
	at com.ti.cloudagent.Agent.createModule(Agent.java:171)
	at com.ti.cloudagent.Agent.lambda$createSpecificModule$4(Agent.java:96)
	at java.util.concurrent.CompletableFuture.uniHandle(Unknown Source)
	at java.util.concurrent.CompletableFuture.uniHandleStage(Unknown Source)
	at java.util.concurrent.CompletableFuture.handle(Unknown Source)
	at com.ti.cloudagent.Agent.createSpecificModule(Agent.java:87)
	at com.ti.cloudagent.Agent.createDeviceDetector(Agent.java:76)
	... 16 more

!ENTRY com.ti.ccstudio.debug 4 0 2019-12-15 17:17:24.767
!MESSAGE An internal error was logged by 'com.ti.ccstudio.debug'.
!STACK 0
java.util.concurrent.ExecutionException: org.json.JSONException: Module Closed
	at java.util.concurrent.CompletableFuture.reportGet(Unknown Source)
	at java.util.concurrent.CompletableFuture.get(Unknown Source)
	at com.ti.ccstudio.debug.service.ApplicationService.getConnectedDebugProbes(ApplicationService.java:295)
	at com.ti.ccstudio.debug.service.ApplicationService.detectXDS110ConnectedProbes(ApplicationService.java:356)
	at com.ti.ccstudio.debug.service.ApplicationService.initDebugger(ApplicationService.java:418)
	at com.ti.ccstudio.debug.service.ApplicationService.access$0(ApplicationService.java:408)
	at com.ti.ccstudio.debug.service.ApplicationService$ThreadContextCache.retrieve(ApplicationService.java:136)
	at com.ti.ccstudio.debug.dsf.extensions.concurrent.DataCache.wait(DataCache.java:59)
	at com.ti.ccstudio.debug.service.ApplicationService.getCpuBeingDebugged(ApplicationService.java:1057)
	at com.ti.ccstudio.debug.launch.CCSLaunchDelegate$2.execute(CCSLaunchDelegate.java:139)
	at org.eclipse.cdt.dsf.concurrent.Query.run(Query.java:177)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: org.json.JSONException: Module Closed
	at com.ti.cloudagent.communication.JSONInterface.call(JSONInterface.java:54)
	at com.ti.cloudagent.Agent.createModule(Agent.java:171)
	at com.ti.cloudagent.Agent.lambda$createSpecificModule$4(Agent.java:96)
	at java.util.concurrent.CompletableFuture.uniHandle(Unknown Source)
	at java.util.concurrent.CompletableFuture.uniHandleStage(Unknown Source)
	at java.util.concurrent.CompletableFuture.handle(Unknown Source)
	at com.ti.cloudagent.Agent.createSpecificModule(Agent.java:87)
	at com.ti.cloudagent.Agent.createDeviceDetector(Agent.java:76)
	... 16 more

!ENTRY com.ti.ccstudio.debug 4 0 2019-12-15 17:17:45.379
!MESSAGE An internal error was logged by 'com.ti.ccstudio.debug'.
!STACK 0
java.util.concurrent.ExecutionException: org.json.JSONException: Module Closed
	at java.util.concurrent.CompletableFuture.reportGet(Unknown Source)
	at java.util.concurrent.CompletableFuture.get(Unknown Source)
	at com.ti.ccstudio.debug.service.ApplicationService.getConnectedDebugProbes(ApplicationService.java:295)
	at com.ti.ccstudio.debug.service.ApplicationService.detectXDS110ConnectedProbes(ApplicationService.java:356)
	at com.ti.ccstudio.debug.service.ApplicationService.initDebugger(ApplicationService.java:418)
	at com.ti.ccstudio.debug.service.ApplicationService.access$0(ApplicationService.java:408)
	at com.ti.ccstudio.debug.service.ApplicationService$ThreadContextCache.retrieve(ApplicationService.java:136)
	at com.ti.ccstudio.debug.dsf.extensions.concurrent.DataCache.wait(DataCache.java:59)
	at com.ti.ccstudio.debug.service.ApplicationService.getCpuBeingDebugged(ApplicationService.java:1057)
	at com.ti.ccstudio.debug.launch.CCSLaunchDelegate$2.execute(CCSLaunchDelegate.java:139)
	at org.eclipse.cdt.dsf.concurrent.Query.run(Query.java:177)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: org.json.JSONException: Module Closed
	at com.ti.cloudagent.communication.JSONInterface.call(JSONInterface.java:54)
	at com.ti.cloudagent.Agent.createModule(Agent.java:171)
	at com.ti.cloudagent.Agent.lambda$createSpecificModule$4(Agent.java:96)
	at java.util.concurrent.CompletableFuture.uniHandle(Unknown Source)
	at java.util.concurrent.CompletableFuture.uniHandleStage(Unknown Source)
	at java.util.concurrent.CompletableFuture.handle(Unknown Source)
	at com.ti.cloudagent.Agent.createSpecificModule(Agent.java:87)
	at com.ti.cloudagent.Agent.createDeviceDetector(Agent.java:76)
	... 16 more

!ENTRY com.ti.ccstudio.debug 4 0 2019-12-15 17:19:32.007
!MESSAGE An internal error was logged by 'com.ti.ccstudio.debug'.
!STACK 0
java.util.concurrent.ExecutionException: org.json.JSONException: Module Closed
	at java.util.concurrent.CompletableFuture.reportGet(Unknown Source)
	at java.util.concurrent.CompletableFuture.get(Unknown Source)
	at com.ti.ccstudio.debug.service.ApplicationService.getConnectedDebugProbes(ApplicationService.java:295)
	at com.ti.ccstudio.debug.service.ApplicationService.detectXDS110ConnectedProbes(ApplicationService.java:356)
	at com.ti.ccstudio.debug.service.ApplicationService.initDebugger(ApplicationService.java:418)
	at com.ti.ccstudio.debug.service.ApplicationService.access$0(ApplicationService.java:408)
	at com.ti.ccstudio.debug.service.ApplicationService$ThreadContextCache.retrieve(ApplicationService.java:136)
	at com.ti.ccstudio.debug.dsf.extensions.concurrent.DataCache.wait(DataCache.java:59)
	at com.ti.ccstudio.debug.service.ApplicationService.getCpuBeingDebugged(ApplicationService.java:1057)
	at com.ti.ccstudio.debug.launch.CCSLaunchDelegate$2.execute(CCSLaunchDelegate.java:139)
	at org.eclipse.cdt.dsf.concurrent.Query.run(Query.java:177)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: org.json.JSONException: Module Closed
	at com.ti.cloudagent.communication.JSONInterface.call(JSONInterface.java:54)
	at com.ti.cloudagent.Agent.createModule(Agent.java:171)
	at com.ti.cloudagent.Agent.lambda$createSpecificModule$4(Agent.java:96)
	at java.util.concurrent.CompletableFuture.uniHandle(Unknown Source)
	at java.util.concurrent.CompletableFuture.uniHandleStage(Unknown Source)
	at java.util.concurrent.CompletableFuture.handle(Unknown Source)
	at com.ti.cloudagent.Agent.createSpecificModule(Agent.java:87)
	at com.ti.cloudagent.Agent.createDeviceDetector(Agent.java:76)
	... 16 more

!ENTRY com.ti.ccstudio.debug 4 0 2019-12-15 17:20:25.149
!MESSAGE An internal error was logged by 'com.ti.ccstudio.debug'.
!STACK 0
java.util.concurrent.ExecutionException: org.json.JSONException: Module Closed
	at java.util.concurrent.CompletableFuture.reportGet(Unknown Source)
	at java.util.concurrent.CompletableFuture.get(Unknown Source)
	at com.ti.ccstudio.debug.service.ApplicationService.getConnectedDebugProbes(ApplicationService.java:295)
	at com.ti.ccstudio.debug.service.ApplicationService.detectXDS110ConnectedProbes(ApplicationService.java:356)
	at com.ti.ccstudio.debug.service.ApplicationService.initDebugger(ApplicationService.java:418)
	at com.ti.ccstudio.debug.service.ApplicationService.access$0(ApplicationService.java:408)
	at com.ti.ccstudio.debug.service.ApplicationService$ThreadContextCache.retrieve(ApplicationService.java:136)
	at com.ti.ccstudio.debug.dsf.extensions.concurrent.DataCache.wait(DataCache.java:59)
	at com.ti.ccstudio.debug.service.ApplicationService.getCpuBeingDebugged(ApplicationService.java:1057)
	at com.ti.ccstudio.debug.launch.CCSLaunchDelegate$2.execute(CCSLaunchDelegate.java:139)
	at org.eclipse.cdt.dsf.concurrent.Query.run(Query.java:177)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: org.json.JSONException: Module Closed
	at com.ti.cloudagent.communication.JSONInterface.call(JSONInterface.java:54)
	at com.ti.cloudagent.Agent.createModule(Agent.java:171)
	at com.ti.cloudagent.Agent.lambda$createSpecificModule$4(Agent.java:96)
	at java.util.concurrent.CompletableFuture.uniHandle(Unknown Source)
	at java.util.concurrent.CompletableFuture.uniHandleStage(Unknown Source)
	at java.util.concurrent.CompletableFuture.handle(Unknown Source)
	at com.ti.cloudagent.Agent.createSpecificModule(Agent.java:87)
	at com.ti.cloudagent.Agent.createDeviceDetector(Agent.java:76)
	... 16 more

!ENTRY com.ti.ccstudio.debug 4 0 2019-12-15 17:21:03.004
!MESSAGE An internal error was logged by 'com.ti.ccstudio.debug'.
!STACK 0
java.util.concurrent.ExecutionException: org.json.JSONException: Module Closed
	at java.util.concurrent.CompletableFuture.reportGet(Unknown Source)
	at java.util.concurrent.CompletableFuture.get(Unknown Source)
	at com.ti.ccstudio.debug.service.ApplicationService.getConnectedDebugProbes(ApplicationService.java:295)
	at com.ti.ccstudio.debug.service.ApplicationService.detectXDS110ConnectedProbes(ApplicationService.java:356)
	at com.ti.ccstudio.debug.service.ApplicationService.initDebugger(ApplicationService.java:418)
	at com.ti.ccstudio.debug.service.ApplicationService.access$0(ApplicationService.java:408)
	at com.ti.ccstudio.debug.service.ApplicationService$ThreadContextCache.retrieve(ApplicationService.java:136)
	at com.ti.ccstudio.debug.dsf.extensions.concurrent.DataCache.wait(DataCache.java:59)
	at com.ti.ccstudio.debug.service.ApplicationService.getCpuBeingDebugged(ApplicationService.java:1057)
	at com.ti.ccstudio.debug.launch.CCSLaunchDelegate$2.execute(CCSLaunchDelegate.java:139)
	at org.eclipse.cdt.dsf.concurrent.Query.run(Query.java:177)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: org.json.JSONException: Module Closed
	at com.ti.cloudagent.communication.JSONInterface.call(JSONInterface.java:54)
	at com.ti.cloudagent.Agent.createModule(Agent.java:171)
	at com.ti.cloudagent.Agent.lambda$createSpecificModule$4(Agent.java:96)
	at java.util.concurrent.CompletableFuture.uniHandle(Unknown Source)
	at java.util.concurrent.CompletableFuture.uniHandleStage(Unknown Source)
	at java.util.concurrent.CompletableFuture.handle(Unknown Source)
	at com.ti.cloudagent.Agent.createSpecificModule(Agent.java:87)
	at com.ti.cloudagent.Agent.createDeviceDetector(Agent.java:76)
	... 16 more

!ENTRY com.ti.ccstudio.debug 4 0 2019-12-15 17:21:29.454
!MESSAGE An internal error was logged by 'com.ti.ccstudio.debug'.
!STACK 0
java.util.concurrent.ExecutionException: org.json.JSONException: Module Closed
	at java.util.concurrent.CompletableFuture.reportGet(Unknown Source)
	at java.util.concurrent.CompletableFuture.get(Unknown Source)
	at com.ti.ccstudio.debug.service.ApplicationService.getConnectedDebugProbes(ApplicationService.java:295)
	at com.ti.ccstudio.debug.service.ApplicationService.detectXDS110ConnectedProbes(ApplicationService.java:356)
	at com.ti.ccstudio.debug.service.ApplicationService.initDebugger(ApplicationService.java:418)
	at com.ti.ccstudio.debug.service.ApplicationService.access$0(ApplicationService.java:408)
	at com.ti.ccstudio.debug.service.ApplicationService$ThreadContextCache.retrieve(ApplicationService.java:136)
	at com.ti.ccstudio.debug.dsf.extensions.concurrent.DataCache.wait(DataCache.java:59)
	at com.ti.ccstudio.debug.service.ApplicationService.getCpuBeingDebugged(ApplicationService.java:1057)
	at com.ti.ccstudio.debug.launch.CCSLaunchDelegate$2.execute(CCSLaunchDelegate.java:139)
	at org.eclipse.cdt.dsf.concurrent.Query.run(Query.java:177)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: org.json.JSONException: Module Closed
	at com.ti.cloudagent.communication.JSONInterface.call(JSONInterface.java:54)
	at com.ti.cloudagent.Agent.createModule(Agent.java:171)
	at com.ti.cloudagent.Agent.lambda$createSpecificModule$4(Agent.java:96)
	at java.util.concurrent.CompletableFuture.uniHandle(Unknown Source)
	at java.util.concurrent.CompletableFuture.uniHandleStage(Unknown Source)
	at java.util.concurrent.CompletableFuture.handle(Unknown Source)
	at com.ti.cloudagent.Agent.createSpecificModule(Agent.java:87)
	at com.ti.cloudagent.Agent.createDeviceDetector(Agent.java:76)
	... 16 more

!ENTRY com.ti.ccstudio.debug 4 0 2019-12-15 17:32:29.659
!MESSAGE An internal error was logged by 'com.ti.ccstudio.debug'.
!STACK 0
java.util.concurrent.ExecutionException: org.json.JSONException: Module Closed
	at java.util.concurrent.CompletableFuture.reportGet(Unknown Source)
	at java.util.concurrent.CompletableFuture.get(Unknown Source)
	at com.ti.ccstudio.debug.service.ApplicationService.getConnectedDebugProbes(ApplicationService.java:295)
	at com.ti.ccstudio.debug.service.ApplicationService.detectXDS110ConnectedProbes(ApplicationService.java:356)
	at com.ti.ccstudio.debug.service.ApplicationService.initDebugger(ApplicationService.java:418)
	at com.ti.ccstudio.debug.service.ApplicationService.access$0(ApplicationService.java:408)
	at com.ti.ccstudio.debug.service.ApplicationService$ThreadContextCache.retrieve(ApplicationService.java:136)
	at com.ti.ccstudio.debug.dsf.extensions.concurrent.DataCache.wait(DataCache.java:59)
	at com.ti.ccstudio.debug.service.ApplicationService.getCpuBeingDebugged(ApplicationService.java:1057)
	at com.ti.ccstudio.debug.launch.CCSLaunchDelegate$2.execute(CCSLaunchDelegate.java:139)
	at org.eclipse.cdt.dsf.concurrent.Query.run(Query.java:177)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: org.json.JSONException: Module Closed
	at com.ti.cloudagent.communication.JSONInterface.call(JSONInterface.java:54)
	at com.ti.cloudagent.Agent.createModule(Agent.java:171)
	at com.ti.cloudagent.Agent.lambda$createSpecificModule$4(Agent.java:96)
	at java.util.concurrent.CompletableFuture.uniHandle(Unknown Source)
	at java.util.concurrent.CompletableFuture.uniHandleStage(Unknown Source)
	at java.util.concurrent.CompletableFuture.handle(Unknown Source)
	at com.ti.cloudagent.Agent.createSpecificModule(Agent.java:87)
	at com.ti.cloudagent.Agent.createDeviceDetector(Agent.java:76)
	... 16 more
!SESSION 2019-12-15 17:38:56.119 -----------------------------------------------
eclipse.buildId=4.8.0.I20180611-0500
java.version=1.8.0_144
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en_US
Framework arguments:  -product com.ti.ccstudio.branding.product
Command-line arguments:  -os win32 -ws win32 -arch x86_64 -product com.ti.ccstudio.branding.product

!ENTRY org.eclipse.core.resources 2 10035 2019-12-15 17:38:59.238
!MESSAGE The workspace exited with unsaved changes in the previous session; refreshing workspace to recover changes.

!ENTRY com.ti.common.core 1 0 2019-12-15 17:38:59.740
!MESSAGE path=ccs_base/DebugServer

!ENTRY com.ti.common.core 1 0 2019-12-15 17:38:59.747
!MESSAGE debugServerDir=C:/ti/ccs910/ccs/ccs_base/DebugServer

!ENTRY org.eclipse.launchbar.core 2 0 2019-12-15 17:39:22.676
!MESSAGE Enablement expression is missing for descriptor type org.eclipse.cdt.debug.core.coreBuildDescriptorType

!ENTRY org.eclipse.launchbar.core 2 0 2019-12-15 17:39:22.698
!MESSAGE Enablement expression is missing for config provider for org.eclipse.cdt.debug.core.coreBuildDescriptorType

!ENTRY org.eclipse.launchbar.core 2 0 2019-12-15 17:39:22.713
!MESSAGE Enablement expression is missing for config provider for org.eclipse.cdt.debug.core.coreBuildDescriptorType

!ENTRY com.ti.ccstudio.ui 1 0 2019-12-15 17:39:23.655
!MESSAGE CCS IDE session started!
	CCS build: 9.1.0.00010
	CCS location: C:/ti/ccs910/ccs
	Workspace location: C:/Users/Alan/Downloads/tirslk_max_1_00_00

!ENTRY com.ti.dbgtrc.webapp.CloudTraceInterface 0 0 2019-12-15 17:39:24.120
!MESSAGE constructor

!ENTRY com.ti.dbgtrc.webapp.CloudTraceInterface 0 0 2019-12-15 17:39:24.132
!MESSAGE done with directories

!ENTRY com.ti.dbgtrc.webapp.CloudTraceInterface 0 0 2019-12-15 17:39:24.175
!MESSAGE loading ti_logger

!ENTRY com.ti.dbgtrc.webapp.CloudTraceInterface 0 0 2019-12-15 17:39:24.184
!MESSAGE Platform os: win32

!ENTRY com.ti.dbgtrc.webapp.CloudTraceInterface 0 0 2019-12-15 17:39:24.200
!MESSAGE loading cToolsIF

!ENTRY com.ti.dbgtrc.webapp.CloudTraceInterface 0 0 2019-12-15 17:39:24.254
!MESSAGE loading cTools

!ENTRY com.ti.dbgtrc.webapp.CloudTraceInterface 0 0 2019-12-15 17:39:24.302
!MESSAGE loading TraceFactory

!ENTRY com.ti.dbgtrc.webapp.CloudTraceInterface 0 0 2019-12-15 17:39:24.354
!MESSAGE loading sqlite3

!ENTRY com.ti.dbgtrc.webapp.CloudTraceInterface 0 0 2019-12-15 17:39:24.414
!MESSAGE loading CloudTrace

!ENTRY com.ti.dbgtrc.webapp.CloudTraceInterface 0 0 2019-12-15 17:39:24.540
!MESSAGE CloudTrace interface loaded

!ENTRY com.ti.ccstudio.debug.server 4 214294189 2019-12-15 17:39:24.561
!MESSAGE Unexpected CCS exit detected [12/14/19 5:09 PM]!!!

!ENTRY com.ti.ccstudio.debug 1 0 2019-12-15 18:18:21.254
!MESSAGE DS_ERROR: CORTEX_M4_0: JTAG Communication Error: (Error -261 @ 0x0) Invalid response was received from the XDS110. (Emulation package 8.3.0.00003) 


!ENTRY com.ti.ccstudio.debug 1 0 2019-12-15 18:18:21.275
!MESSAGE DS_ERROR: CORTEX_M4_0: Failed to remove the debug state from the target before disconnecting.  There may still be breakpoint op-codes embedded in program memory.  It is recommended that you reset the emulator before you connect and reload your program before you continue debugging


!ENTRY com.ti.ccstudio.debug 4 0 2019-12-15 20:17:19.648
!MESSAGE An internal error was logged by 'com.ti.ccstudio.debug'.
!STACK 0
java.util.concurrent.ExecutionException: org.json.JSONException: Module Closed
	at java.util.concurrent.CompletableFuture.reportGet(Unknown Source)
	at java.util.concurrent.CompletableFuture.get(Unknown Source)
	at com.ti.ccstudio.debug.service.ApplicationService.getConnectedDebugProbes(ApplicationService.java:295)
	at com.ti.ccstudio.debug.service.ApplicationService.detectXDS110ConnectedProbes(ApplicationService.java:356)
	at com.ti.ccstudio.debug.service.ApplicationService.initDebugger(ApplicationService.java:418)
	at com.ti.ccstudio.debug.service.ApplicationService.access$0(ApplicationService.java:408)
	at com.ti.ccstudio.debug.service.ApplicationService$ThreadContextCache.retrieve(ApplicationService.java:136)
	at com.ti.ccstudio.debug.dsf.extensions.concurrent.DataCache.wait(DataCache.java:59)
	at com.ti.ccstudio.debug.service.ApplicationService.getCpuBeingDebugged(ApplicationService.java:1057)
	at com.ti.ccstudio.debug.launch.CCSLaunchDelegate$2.execute(CCSLaunchDelegate.java:139)
	at org.eclipse.cdt.dsf.concurrent.Query.run(Query.java:177)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: org.json.JSONException: Module Closed
	at com.ti.cloudagent.communication.JSONInterface.call(JSONInterface.java:54)
	at com.ti.cloudagent.Agent.createModule(Agent.java:171)
	at com.ti.cloudagent.Agent.lambda$createSpecificModule$4(Agent.java:96)
	at java.util.concurrent.CompletableFuture.uniHandle(Unknown Source)
	at java.util.concurrent.CompletableFuture.uniHandleStage(Unknown Source)
	at java.util.concurrent.CompletableFuture.handle(Unknown Source)
	at com.ti.cloudagent.Agent.createSpecificModule(Agent.java:87)
	at com.ti.cloudagent.Agent.createDeviceDetector(Agent.java:76)
	... 16 more

!ENTRY com.ti.ccstudio.debug 1 0 2019-12-15 20:17:39.912
!MESSAGE DS_ERROR: CORTEX_M4_0: JTAG Communication Error: (Error -261 @ 0x0) Invalid response was received from the XDS110. (Emulation package 8.3.0.00003) 


!ENTRY com.ti.ccstudio.debug 1 0 2019-12-15 20:17:39.972
!MESSAGE DS_ERROR: CORTEX_M4_0: Failed to remove the debug state from the target before disconnecting.  There may still be breakpoint op-codes embedded in program memory.  It is recommended that you reset the emulator before you connect and reload your program before you continue debugging


!ENTRY com.ti.ccstudio.debug 4 0 2019-12-15 20:19:57.663
!MESSAGE An internal error was logged by 'com.ti.ccstudio.debug'.
!STACK 0
java.util.concurrent.ExecutionException: org.json.JSONException: Module Closed
	at java.util.concurrent.CompletableFuture.reportGet(Unknown Source)
	at java.util.concurrent.CompletableFuture.get(Unknown Source)
	at com.ti.ccstudio.debug.service.ApplicationService.getConnectedDebugProbes(ApplicationService.java:295)
	at com.ti.ccstudio.debug.service.ApplicationService.detectXDS110ConnectedProbes(ApplicationService.java:356)
	at com.ti.ccstudio.debug.service.ApplicationService.initDebugger(ApplicationService.java:418)
	at com.ti.ccstudio.debug.service.ApplicationService.access$0(ApplicationService.java:408)
	at com.ti.ccstudio.debug.service.ApplicationService$ThreadContextCache.retrieve(ApplicationService.java:136)
	at com.ti.ccstudio.debug.dsf.extensions.concurrent.DataCache.wait(DataCache.java:59)
	at com.ti.ccstudio.debug.service.ApplicationService.getCpuBeingDebugged(ApplicationService.java:1057)
	at com.ti.ccstudio.debug.launch.CCSLaunchDelegate$2.execute(CCSLaunchDelegate.java:139)
	at org.eclipse.cdt.dsf.concurrent.Query.run(Query.java:177)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: org.json.JSONException: Module Closed
	at com.ti.cloudagent.communication.JSONInterface.call(JSONInterface.java:54)
	at com.ti.cloudagent.Agent.createModule(Agent.java:171)
	at com.ti.cloudagent.Agent.lambda$createSpecificModule$4(Agent.java:96)
	at java.util.concurrent.CompletableFuture.uniHandle(Unknown Source)
	at java.util.concurrent.CompletableFuture.uniHandleStage(Unknown Source)
	at java.util.concurrent.CompletableFuture.handle(Unknown Source)
	at com.ti.cloudagent.Agent.createSpecificModule(Agent.java:87)
	at com.ti.cloudagent.Agent.createDeviceDetector(Agent.java:76)
	... 16 more

!ENTRY com.ti.ccstudio.debug 1 0 2019-12-15 20:20:14.142
!MESSAGE DS_ERROR: CORTEX_M4_0: JTAG Communication Error: (Error -613 @ 0x0) The target indicates that it is busy.  Either try the SWD request  again, or abort the transaction. (Emulation package 8.3.0.00003) 


!ENTRY com.ti.ccstudio.debug 1 0 2019-12-15 20:20:14.189
!MESSAGE DS_ERROR: CORTEX_M4_0: Failed to remove the debug state from the target before disconnecting.  There may still be breakpoint op-codes embedded in program memory.  It is recommended that you reset the emulator before you connect and reload your program before you continue debugging


!ENTRY com.ti.ccstudio.debug 4 0 2019-12-15 20:21:02.626
!MESSAGE An internal error was logged by 'com.ti.ccstudio.debug'.
!STACK 0
java.util.concurrent.ExecutionException: org.json.JSONException: Module Closed
	at java.util.concurrent.CompletableFuture.reportGet(Unknown Source)
	at java.util.concurrent.CompletableFuture.get(Unknown Source)
	at com.ti.ccstudio.debug.service.ApplicationService.getConnectedDebugProbes(ApplicationService.java:295)
	at com.ti.ccstudio.debug.service.ApplicationService.detectXDS110ConnectedProbes(ApplicationService.java:356)
	at com.ti.ccstudio.debug.service.ApplicationService.initDebugger(ApplicationService.java:418)
	at com.ti.ccstudio.debug.service.ApplicationService.access$0(ApplicationService.java:408)
	at com.ti.ccstudio.debug.service.ApplicationService$ThreadContextCache.retrieve(ApplicationService.java:136)
	at com.ti.ccstudio.debug.dsf.extensions.concurrent.DataCache.wait(DataCache.java:59)
	at com.ti.ccstudio.debug.service.ApplicationService.getCpuBeingDebugged(ApplicationService.java:1057)
	at com.ti.ccstudio.debug.launch.CCSLaunchDelegate$2.execute(CCSLaunchDelegate.java:139)
	at org.eclipse.cdt.dsf.concurrent.Query.run(Query.java:177)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: org.json.JSONException: Module Closed
	at com.ti.cloudagent.communication.JSONInterface.call(JSONInterface.java:54)
	at com.ti.cloudagent.Agent.createModule(Agent.java:171)
	at com.ti.cloudagent.Agent.lambda$createSpecificModule$4(Agent.java:96)
	at java.util.concurrent.CompletableFuture.uniHandle(Unknown Source)
	at java.util.concurrent.CompletableFuture.uniHandleStage(Unknown Source)
	at java.util.concurrent.CompletableFuture.handle(Unknown Source)
	at com.ti.cloudagent.Agent.createSpecificModule(Agent.java:87)
	at com.ti.cloudagent.Agent.createDeviceDetector(Agent.java:76)
	... 16 more

!ENTRY com.ti.ccstudio.debug 1 0 2019-12-15 20:21:02.954
!MESSAGE DS_ERROR: CS_DAP_0: Error connecting to the target: (Error -614 @ 0x0) The target indicates there is an error condition from a previous SWD  request. Clear the error the condition, and try the SWD request again. (Emulation package 8.3.0.00003) 


!ENTRY com.ti.ccstudio.debug 1 0 2019-12-15 20:21:03.225
!MESSAGE DS_ERROR: Error connecting to the target:
(Error -614 @ 0x0)
The target indicates there is an error condition from a previous SWD 
request. Clear the error the condition, and try the SWD request again.
(Emulation package 8.3.0.00003)


!ENTRY com.ti.ccstudio.debug 1 0 2019-12-15 20:21:09.738
!MESSAGE DS_ERROR: CS_DAP_0: Error connecting to the target: (Error -260 @ 0x0) An attempt to connect to the XDS110 failed. The cause may be one or more of: no XDS110 is connected, invalid firmware update, invalid XDS110 serial number, or faulty USB cable. The firmware and serial number may be updated using the xdsdfu utility found in the .../ccs_base/common/uscif/xds110 directory of your installation. View the ReadMe.txt file there for instructions. (Emulation package 8.3.0.00003) 


!ENTRY com.ti.ccstudio.debug 1 0 2019-12-15 20:21:09.788
!MESSAGE DS_ERROR: Error connecting to the target:
(Error -260 @ 0x0)
An attempt to connect to the XDS110 failed.
The cause may be one or more of: no XDS110 is connected, invalid
firmware update, invalid XDS110 serial number, or faulty USB
cable. The firmware and serial number may be updated using the
xdsdfu utility found in the .../ccs_base/common/uscif/xds110
directory of your installation. View the ReadMe.txt file there
for instructions.
(Emulation package 8.3.0.00003)


!ENTRY com.ti.ccstudio.debug 1 0 2019-12-15 20:21:15.597
!MESSAGE DS_ERROR: CS_DAP_0: Error connecting to the target: (Error -614 @ 0x0) The target indicates there is an error condition from a previous SWD  request. Clear the error the condition, and try the SWD request again. (Emulation package 8.3.0.00003) 


!ENTRY com.ti.ccstudio.debug 1 0 2019-12-15 20:21:15.612
!MESSAGE DS_ERROR: Error connecting to the target:
(Error -614 @ 0x0)
The target indicates there is an error condition from a previous SWD 
request. Clear the error the condition, and try the SWD request again.
(Emulation package 8.3.0.00003)


!ENTRY com.ti.ccstudio.debug 1 0 2019-12-15 20:21:16.778
!MESSAGE DS_ERROR: CS_DAP_0: Error connecting to the target: (Error -614 @ 0x0) The target indicates there is an error condition from a previous SWD  request. Clear the error the condition, and try the SWD request again. (Emulation package 8.3.0.00003) 


!ENTRY com.ti.ccstudio.debug 1 0 2019-12-15 20:21:16.810
!MESSAGE DS_ERROR: Error connecting to the target:
(Error -614 @ 0x0)
The target indicates there is an error condition from a previous SWD 
request. Clear the error the condition, and try the SWD request again.
(Emulation package 8.3.0.00003)


!ENTRY com.ti.ccstudio.debug 1 0 2019-12-15 20:21:27.659
!MESSAGE DS_ERROR: CS_DAP_0: Error connecting to the target: (Error -614 @ 0x0) The target indicates there is an error condition from a previous SWD  request. Clear the error the condition, and try the SWD request again. (Emulation package 8.3.0.00003) 


!ENTRY com.ti.ccstudio.debug 1 0 2019-12-15 20:21:27.690
!MESSAGE DS_ERROR: Error connecting to the target:
(Error -614 @ 0x0)
The target indicates there is an error condition from a previous SWD 
request. Clear the error the condition, and try the SWD request again.
(Emulation package 8.3.0.00003)


!ENTRY com.ti.ccstudio.debug 1 0 2019-12-15 20:21:35.836
!MESSAGE DS_ERROR: CS_DAP_0: Error connecting to the target: (Error -614 @ 0x0) The target indicates there is an error condition from a previous SWD  request. Clear the error the condition, and try the SWD request again. (Emulation package 8.3.0.00003) 


!ENTRY com.ti.ccstudio.debug 1 0 2019-12-15 20:21:35.867
!MESSAGE DS_ERROR: Error connecting to the target:
(Error -614 @ 0x0)
The target indicates there is an error condition from a previous SWD 
request. Clear the error the condition, and try the SWD request again.
(Emulation package 8.3.0.00003)


!ENTRY com.ti.ccstudio.debug 1 0 2019-12-15 20:21:36.940
!MESSAGE DS_ERROR: CS_DAP_0: Error connecting to the target: (Error -614 @ 0x0) The target indicates there is an error condition from a previous SWD  request. Clear the error the condition, and try the SWD request again. (Emulation package 8.3.0.00003) 


!ENTRY com.ti.ccstudio.debug 1 0 2019-12-15 20:21:36.955
!MESSAGE DS_ERROR: Error connecting to the target:
(Error -614 @ 0x0)
The target indicates there is an error condition from a previous SWD 
request. Clear the error the condition, and try the SWD request again.
(Emulation package 8.3.0.00003)


!ENTRY com.ti.ccstudio.debug 1 0 2019-12-15 20:21:41.766
!MESSAGE DS_ERROR: CS_DAP_0: Error connecting to the target: (Error -260 @ 0x0) An attempt to connect to the XDS110 failed. The cause may be one or more of: no XDS110 is connected, invalid firmware update, invalid XDS110 serial number, or faulty USB cable. The firmware and serial number may be updated using the xdsdfu utility found in the .../ccs_base/common/uscif/xds110 directory of your installation. View the ReadMe.txt file there for instructions. (Emulation package 8.3.0.00003) 


!ENTRY com.ti.ccstudio.debug 1 0 2019-12-15 20:21:41.797
!MESSAGE DS_ERROR: Error connecting to the target:
(Error -260 @ 0x0)
An attempt to connect to the XDS110 failed.
The cause may be one or more of: no XDS110 is connected, invalid
firmware update, invalid XDS110 serial number, or faulty USB
cable. The firmware and serial number may be updated using the
xdsdfu utility found in the .../ccs_base/common/uscif/xds110
directory of your installation. View the ReadMe.txt file there
for instructions.
(Emulation package 8.3.0.00003)


!ENTRY com.ti.ccstudio.debug 4 0 2019-12-15 20:25:40.905
!MESSAGE An internal error was logged by 'com.ti.ccstudio.debug'.
!STACK 0
java.util.concurrent.ExecutionException: org.json.JSONException: Module Closed
	at java.util.concurrent.CompletableFuture.reportGet(Unknown Source)
	at java.util.concurrent.CompletableFuture.get(Unknown Source)
	at com.ti.ccstudio.debug.service.ApplicationService.getConnectedDebugProbes(ApplicationService.java:295)
	at com.ti.ccstudio.debug.service.ApplicationService.detectXDS110ConnectedProbes(ApplicationService.java:356)
	at com.ti.ccstudio.debug.service.ApplicationService.initDebugger(ApplicationService.java:418)
	at com.ti.ccstudio.debug.service.ApplicationService.access$0(ApplicationService.java:408)
	at com.ti.ccstudio.debug.service.ApplicationService$ThreadContextCache.retrieve(ApplicationService.java:136)
	at com.ti.ccstudio.debug.dsf.extensions.concurrent.DataCache.wait(DataCache.java:59)
	at com.ti.ccstudio.debug.service.ApplicationService.getCpuBeingDebugged(ApplicationService.java:1057)
	at com.ti.ccstudio.debug.launch.CCSLaunchDelegate$2.execute(CCSLaunchDelegate.java:139)
	at org.eclipse.cdt.dsf.concurrent.Query.run(Query.java:177)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: org.json.JSONException: Module Closed
	at com.ti.cloudagent.communication.JSONInterface.call(JSONInterface.java:54)
	at com.ti.cloudagent.Agent.createModule(Agent.java:171)
	at com.ti.cloudagent.Agent.lambda$createSpecificModule$4(Agent.java:96)
	at java.util.concurrent.CompletableFuture.uniHandle(Unknown Source)
	at java.util.concurrent.CompletableFuture.uniHandleStage(Unknown Source)
	at java.util.concurrent.CompletableFuture.handle(Unknown Source)
	at com.ti.cloudagent.Agent.createSpecificModule(Agent.java:87)
	at com.ti.cloudagent.Agent.createDeviceDetector(Agent.java:76)
	... 16 more

!ENTRY com.ti.ccstudio.debug 4 0 2019-12-15 20:29:57.044
!MESSAGE An internal error was logged by 'com.ti.ccstudio.debug'.
!STACK 0
java.util.concurrent.ExecutionException: org.json.JSONException: Module Closed
	at java.util.concurrent.CompletableFuture.reportGet(Unknown Source)
	at java.util.concurrent.CompletableFuture.get(Unknown Source)
	at com.ti.ccstudio.debug.service.ApplicationService.getConnectedDebugProbes(ApplicationService.java:295)
	at com.ti.ccstudio.debug.service.ApplicationService.detectXDS110ConnectedProbes(ApplicationService.java:356)
	at com.ti.ccstudio.debug.service.ApplicationService.initDebugger(ApplicationService.java:418)
	at com.ti.ccstudio.debug.service.ApplicationService.access$0(ApplicationService.java:408)
	at com.ti.ccstudio.debug.service.ApplicationService$ThreadContextCache.retrieve(ApplicationService.java:136)
	at com.ti.ccstudio.debug.dsf.extensions.concurrent.DataCache.wait(DataCache.java:59)
	at com.ti.ccstudio.debug.service.ApplicationService.getCpuBeingDebugged(ApplicationService.java:1057)
	at com.ti.ccstudio.debug.launch.CCSLaunchDelegate$2.execute(CCSLaunchDelegate.java:139)
	at org.eclipse.cdt.dsf.concurrent.Query.run(Query.java:177)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: org.json.JSONException: Module Closed
	at com.ti.cloudagent.communication.JSONInterface.call(JSONInterface.java:54)
	at com.ti.cloudagent.Agent.createModule(Agent.java:171)
	at com.ti.cloudagent.Agent.lambda$createSpecificModule$4(Agent.java:96)
	at java.util.concurrent.CompletableFuture.uniHandle(Unknown Source)
	at java.util.concurrent.CompletableFuture.uniHandleStage(Unknown Source)
	at java.util.concurrent.CompletableFuture.handle(Unknown Source)
	at com.ti.cloudagent.Agent.createSpecificModule(Agent.java:87)
	at com.ti.cloudagent.Agent.createDeviceDetector(Agent.java:76)
	... 16 more

!ENTRY com.ti.ccstudio.debug 4 0 2019-12-15 20:30:58.683
!MESSAGE An internal error was logged by 'com.ti.ccstudio.debug'.
!STACK 0
java.util.concurrent.ExecutionException: org.json.JSONException: Module Closed
	at java.util.concurrent.CompletableFuture.reportGet(Unknown Source)
	at java.util.concurrent.CompletableFuture.get(Unknown Source)
	at com.ti.ccstudio.debug.service.ApplicationService.getConnectedDebugProbes(ApplicationService.java:295)
	at com.ti.ccstudio.debug.service.ApplicationService.detectXDS110ConnectedProbes(ApplicationService.java:356)
	at com.ti.ccstudio.debug.service.ApplicationService.initDebugger(ApplicationService.java:418)
	at com.ti.ccstudio.debug.service.ApplicationService.access$0(ApplicationService.java:408)
	at com.ti.ccstudio.debug.service.ApplicationService$ThreadContextCache.retrieve(ApplicationService.java:136)
	at com.ti.ccstudio.debug.dsf.extensions.concurrent.DataCache.wait(DataCache.java:59)
	at com.ti.ccstudio.debug.service.ApplicationService.getCpuBeingDebugged(ApplicationService.java:1057)
	at com.ti.ccstudio.debug.launch.CCSLaunchDelegate$2.execute(CCSLaunchDelegate.java:139)
	at org.eclipse.cdt.dsf.concurrent.Query.run(Query.java:177)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: org.json.JSONException: Module Closed
	at com.ti.cloudagent.communication.JSONInterface.call(JSONInterface.java:54)
	at com.ti.cloudagent.Agent.createModule(Agent.java:171)
	at com.ti.cloudagent.Agent.lambda$createSpecificModule$4(Agent.java:96)
	at java.util.concurrent.CompletableFuture.uniHandle(Unknown Source)
	at java.util.concurrent.CompletableFuture.uniHandleStage(Unknown Source)
	at java.util.concurrent.CompletableFuture.handle(Unknown Source)
	at com.ti.cloudagent.Agent.createSpecificModule(Agent.java:87)
	at com.ti.cloudagent.Agent.createDeviceDetector(Agent.java:76)
	... 16 more

!ENTRY com.ti.ccstudio.debug 4 0 2019-12-15 20:31:59.380
!MESSAGE An internal error was logged by 'com.ti.ccstudio.debug'.
!STACK 0
java.util.concurrent.ExecutionException: org.json.JSONException: Module Closed
	at java.util.concurrent.CompletableFuture.reportGet(Unknown Source)
	at java.util.concurrent.CompletableFuture.get(Unknown Source)
	at com.ti.ccstudio.debug.service.ApplicationService.getConnectedDebugProbes(ApplicationService.java:295)
	at com.ti.ccstudio.debug.service.ApplicationService.detectXDS110ConnectedProbes(ApplicationService.java:356)
	at com.ti.ccstudio.debug.service.ApplicationService.initDebugger(ApplicationService.java:418)
	at com.ti.ccstudio.debug.service.ApplicationService.access$0(ApplicationService.java:408)
	at com.ti.ccstudio.debug.service.ApplicationService$ThreadContextCache.retrieve(ApplicationService.java:136)
	at com.ti.ccstudio.debug.dsf.extensions.concurrent.DataCache.wait(DataCache.java:59)
	at com.ti.ccstudio.debug.service.ApplicationService.getCpuBeingDebugged(ApplicationService.java:1057)
	at com.ti.ccstudio.debug.launch.CCSLaunchDelegate$2.execute(CCSLaunchDelegate.java:139)
	at org.eclipse.cdt.dsf.concurrent.Query.run(Query.java:177)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: org.json.JSONException: Module Closed
	at com.ti.cloudagent.communication.JSONInterface.call(JSONInterface.java:54)
	at com.ti.cloudagent.Agent.createModule(Agent.java:171)
	at com.ti.cloudagent.Agent.lambda$createSpecificModule$4(Agent.java:96)
	at java.util.concurrent.CompletableFuture.uniHandle(Unknown Source)
	at java.util.concurrent.CompletableFuture.uniHandleStage(Unknown Source)
	at java.util.concurrent.CompletableFuture.handle(Unknown Source)
	at com.ti.cloudagent.Agent.createSpecificModule(Agent.java:87)
	at com.ti.cloudagent.Agent.createDeviceDetector(Agent.java:76)
	... 16 more

!ENTRY com.ti.ccstudio.debug 4 0 2019-12-15 20:33:55.011
!MESSAGE An internal error was logged by 'com.ti.ccstudio.debug'.
!STACK 0
java.util.concurrent.ExecutionException: org.json.JSONException: Module Closed
	at java.util.concurrent.CompletableFuture.reportGet(Unknown Source)
	at java.util.concurrent.CompletableFuture.get(Unknown Source)
	at com.ti.ccstudio.debug.service.ApplicationService.getConnectedDebugProbes(ApplicationService.java:295)
	at com.ti.ccstudio.debug.service.ApplicationService.detectXDS110ConnectedProbes(ApplicationService.java:356)
	at com.ti.ccstudio.debug.service.ApplicationService.initDebugger(ApplicationService.java:418)
	at com.ti.ccstudio.debug.service.ApplicationService.access$0(ApplicationService.java:408)
	at com.ti.ccstudio.debug.service.ApplicationService$ThreadContextCache.retrieve(ApplicationService.java:136)
	at com.ti.ccstudio.debug.dsf.extensions.concurrent.DataCache.wait(DataCache.java:59)
	at com.ti.ccstudio.debug.service.ApplicationService.getCpuBeingDebugged(ApplicationService.java:1057)
	at com.ti.ccstudio.debug.launch.CCSLaunchDelegate$2.execute(CCSLaunchDelegate.java:139)
	at org.eclipse.cdt.dsf.concurrent.Query.run(Query.java:177)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: org.json.JSONException: Module Closed
	at com.ti.cloudagent.communication.JSONInterface.call(JSONInterface.java:54)
	at com.ti.cloudagent.Agent.createModule(Agent.java:171)
	at com.ti.cloudagent.Agent.lambda$createSpecificModule$4(Agent.java:96)
	at java.util.concurrent.CompletableFuture.uniHandle(Unknown Source)
	at java.util.concurrent.CompletableFuture.uniHandleStage(Unknown Source)
	at java.util.concurrent.CompletableFuture.handle(Unknown Source)
	at com.ti.cloudagent.Agent.createSpecificModule(Agent.java:87)
	at com.ti.cloudagent.Agent.createDeviceDetector(Agent.java:76)
	... 16 more

!ENTRY com.ti.ccstudio.debug 4 0 2019-12-15 20:34:21.487
!MESSAGE An internal error was logged by 'com.ti.ccstudio.debug'.
!STACK 0
java.util.concurrent.ExecutionException: org.json.JSONException: Module Closed
	at java.util.concurrent.CompletableFuture.reportGet(Unknown Source)
	at java.util.concurrent.CompletableFuture.get(Unknown Source)
	at com.ti.ccstudio.debug.service.ApplicationService.getConnectedDebugProbes(ApplicationService.java:295)
	at com.ti.ccstudio.debug.service.ApplicationService.detectXDS110ConnectedProbes(ApplicationService.java:356)
	at com.ti.ccstudio.debug.service.ApplicationService.initDebugger(ApplicationService.java:418)
	at com.ti.ccstudio.debug.service.ApplicationService.access$0(ApplicationService.java:408)
	at com.ti.ccstudio.debug.service.ApplicationService$ThreadContextCache.retrieve(ApplicationService.java:136)
	at com.ti.ccstudio.debug.dsf.extensions.concurrent.DataCache.wait(DataCache.java:59)
	at com.ti.ccstudio.debug.service.ApplicationService.getCpuBeingDebugged(ApplicationService.java:1057)
	at com.ti.ccstudio.debug.launch.CCSLaunchDelegate$2.execute(CCSLaunchDelegate.java:139)
	at org.eclipse.cdt.dsf.concurrent.Query.run(Query.java:177)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: org.json.JSONException: Module Closed
	at com.ti.cloudagent.communication.JSONInterface.call(JSONInterface.java:54)
	at com.ti.cloudagent.Agent.createModule(Agent.java:171)
	at com.ti.cloudagent.Agent.lambda$createSpecificModule$4(Agent.java:96)
	at java.util.concurrent.CompletableFuture.uniHandle(Unknown Source)
	at java.util.concurrent.CompletableFuture.uniHandleStage(Unknown Source)
	at java.util.concurrent.CompletableFuture.handle(Unknown Source)
	at com.ti.cloudagent.Agent.createSpecificModule(Agent.java:87)
	at com.ti.cloudagent.Agent.createDeviceDetector(Agent.java:76)
	... 16 more

!ENTRY com.ti.ccstudio.debug 4 0 2019-12-15 20:35:55.036
!MESSAGE An internal error was logged by 'com.ti.ccstudio.debug'.
!STACK 0
java.util.concurrent.ExecutionException: org.json.JSONException: Module Closed
	at java.util.concurrent.CompletableFuture.reportGet(Unknown Source)
	at java.util.concurrent.CompletableFuture.get(Unknown Source)
	at com.ti.ccstudio.debug.service.ApplicationService.getConnectedDebugProbes(ApplicationService.java:295)
	at com.ti.ccstudio.debug.service.ApplicationService.detectXDS110ConnectedProbes(ApplicationService.java:356)
	at com.ti.ccstudio.debug.service.ApplicationService.initDebugger(ApplicationService.java:418)
	at com.ti.ccstudio.debug.service.ApplicationService.access$0(ApplicationService.java:408)
	at com.ti.ccstudio.debug.service.ApplicationService$ThreadContextCache.retrieve(ApplicationService.java:136)
	at com.ti.ccstudio.debug.dsf.extensions.concurrent.DataCache.wait(DataCache.java:59)
	at com.ti.ccstudio.debug.service.ApplicationService.getCpuBeingDebugged(ApplicationService.java:1057)
	at com.ti.ccstudio.debug.launch.CCSLaunchDelegate$2.execute(CCSLaunchDelegate.java:139)
	at org.eclipse.cdt.dsf.concurrent.Query.run(Query.java:177)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: org.json.JSONException: Module Closed
	at com.ti.cloudagent.communication.JSONInterface.call(JSONInterface.java:54)
	at com.ti.cloudagent.Agent.createModule(Agent.java:171)
	at com.ti.cloudagent.Agent.lambda$createSpecificModule$4(Agent.java:96)
	at java.util.concurrent.CompletableFuture.uniHandle(Unknown Source)
	at java.util.concurrent.CompletableFuture.uniHandleStage(Unknown Source)
	at java.util.concurrent.CompletableFuture.handle(Unknown Source)
	at com.ti.cloudagent.Agent.createSpecificModule(Agent.java:87)
	at com.ti.cloudagent.Agent.createDeviceDetector(Agent.java:76)
	... 16 more

!ENTRY com.ti.ccstudio.debug 1 0 2019-12-15 20:36:03.802
!MESSAGE DS_ERROR: CORTEX_M4_0: JTAG Communication Error: (Error -613 @ 0x0) The target indicates that it is busy.  Either try the SWD request  again, or abort the transaction. (Emulation package 8.3.0.00003) 


!ENTRY com.ti.ccstudio.debug 1 0 2019-12-15 20:36:03.833
!MESSAGE DS_ERROR: CORTEX_M4_0: Failed to remove the debug state from the target before disconnecting.  There may still be breakpoint op-codes embedded in program memory.  It is recommended that you reset the emulator before you connect and reload your program before you continue debugging


!ENTRY com.ti.ccstudio.debug 4 0 2019-12-15 20:51:25.898
!MESSAGE An internal error was logged by 'com.ti.ccstudio.debug'.
!STACK 0
java.util.concurrent.ExecutionException: org.json.JSONException: Module Closed
	at java.util.concurrent.CompletableFuture.reportGet(Unknown Source)
	at java.util.concurrent.CompletableFuture.get(Unknown Source)
	at com.ti.ccstudio.debug.service.ApplicationService.getConnectedDebugProbes(ApplicationService.java:295)
	at com.ti.ccstudio.debug.service.ApplicationService.detectXDS110ConnectedProbes(ApplicationService.java:356)
	at com.ti.ccstudio.debug.service.ApplicationService.initDebugger(ApplicationService.java:418)
	at com.ti.ccstudio.debug.service.ApplicationService.access$0(ApplicationService.java:408)
	at com.ti.ccstudio.debug.service.ApplicationService$ThreadContextCache.retrieve(ApplicationService.java:136)
	at com.ti.ccstudio.debug.dsf.extensions.concurrent.DataCache.wait(DataCache.java:59)
	at com.ti.ccstudio.debug.service.ApplicationService.getCpuBeingDebugged(ApplicationService.java:1057)
	at com.ti.ccstudio.debug.launch.CCSLaunchDelegate$2.execute(CCSLaunchDelegate.java:139)
	at org.eclipse.cdt.dsf.concurrent.Query.run(Query.java:177)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: org.json.JSONException: Module Closed
	at com.ti.cloudagent.communication.JSONInterface.call(JSONInterface.java:54)
	at com.ti.cloudagent.Agent.createModule(Agent.java:171)
	at com.ti.cloudagent.Agent.lambda$createSpecificModule$4(Agent.java:96)
	at java.util.concurrent.CompletableFuture.uniHandle(Unknown Source)
	at java.util.concurrent.CompletableFuture.uniHandleStage(Unknown Source)
	at java.util.concurrent.CompletableFuture.handle(Unknown Source)
	at com.ti.cloudagent.Agent.createSpecificModule(Agent.java:87)
	at com.ti.cloudagent.Agent.createDeviceDetector(Agent.java:76)
	... 16 more

!ENTRY com.ti.ccstudio.debug 1 0 2019-12-15 20:51:26.252
!MESSAGE DS_ERROR: CS_DAP_0: Error connecting to the target: (Error -614 @ 0x0) The target indicates there is an error condition from a previous SWD  request. Clear the error the condition, and try the SWD request again. (Emulation package 8.3.0.00003) 


!ENTRY com.ti.ccstudio.debug 1 0 2019-12-15 20:51:26.629
!MESSAGE DS_ERROR: Error connecting to the target:
(Error -614 @ 0x0)
The target indicates there is an error condition from a previous SWD 
request. Clear the error the condition, and try the SWD request again.
(Emulation package 8.3.0.00003)


!ENTRY com.ti.ccstudio.debug 1 0 2019-12-15 20:51:57.732
!MESSAGE DS_ERROR: CS_DAP_0: Error connecting to the target: (Error -614 @ 0x0) The target indicates there is an error condition from a previous SWD  request. Clear the error the condition, and try the SWD request again. (Emulation package 8.3.0.00003) 


!ENTRY com.ti.ccstudio.debug 1 0 2019-12-15 20:51:57.763
!MESSAGE DS_ERROR: Error connecting to the target:
(Error -614 @ 0x0)
The target indicates there is an error condition from a previous SWD 
request. Clear the error the condition, and try the SWD request again.
(Emulation package 8.3.0.00003)


!ENTRY com.ti.ccstudio.debug 1 0 2019-12-15 20:52:04.981
!MESSAGE DS_ERROR: CS_DAP_0: Error connecting to the target: (Error -614 @ 0x0) The target indicates there is an error condition from a previous SWD  request. Clear the error the condition, and try the SWD request again. (Emulation package 8.3.0.00003) 


!ENTRY com.ti.ccstudio.debug 1 0 2019-12-15 20:52:04.996
!MESSAGE DS_ERROR: Error connecting to the target:
(Error -614 @ 0x0)
The target indicates there is an error condition from a previous SWD 
request. Clear the error the condition, and try the SWD request again.
(Emulation package 8.3.0.00003)


!ENTRY com.ti.ccstudio.debug 1 0 2019-12-15 20:52:07.953
!MESSAGE DS_ERROR: CS_DAP_0: Error connecting to the target: (Error -614 @ 0x0) The target indicates there is an error condition from a previous SWD  request. Clear the error the condition, and try the SWD request again. (Emulation package 8.3.0.00003) 


!ENTRY com.ti.ccstudio.debug 1 0 2019-12-15 20:52:07.984
!MESSAGE DS_ERROR: Error connecting to the target:
(Error -614 @ 0x0)
The target indicates there is an error condition from a previous SWD 
request. Clear the error the condition, and try the SWD request again.
(Emulation package 8.3.0.00003)


!ENTRY com.ti.ccstudio.debug 1 0 2019-12-15 20:52:11.172
!MESSAGE DS_ERROR: CS_DAP_0: Error connecting to the target: (Error -260 @ 0x0) An attempt to connect to the XDS110 failed. The cause may be one or more of: no XDS110 is connected, invalid firmware update, invalid XDS110 serial number, or faulty USB cable. The firmware and serial number may be updated using the xdsdfu utility found in the .../ccs_base/common/uscif/xds110 directory of your installation. View the ReadMe.txt file there for instructions. (Emulation package 8.3.0.00003) 


!ENTRY com.ti.ccstudio.debug 1 0 2019-12-15 20:52:11.211
!MESSAGE DS_ERROR: Error connecting to the target:
(Error -260 @ 0x0)
An attempt to connect to the XDS110 failed.
The cause may be one or more of: no XDS110 is connected, invalid
firmware update, invalid XDS110 serial number, or faulty USB
cable. The firmware and serial number may be updated using the
xdsdfu utility found in the .../ccs_base/common/uscif/xds110
directory of your installation. View the ReadMe.txt file there
for instructions.
(Emulation package 8.3.0.00003)


!ENTRY com.ti.ccstudio.debug 1 0 2019-12-15 20:52:15.271
!MESSAGE DS_ERROR: CS_DAP_0: Error connecting to the target: (Error -614 @ 0x0) The target indicates there is an error condition from a previous SWD  request. Clear the error the condition, and try the SWD request again. (Emulation package 8.3.0.00003) 


!ENTRY com.ti.ccstudio.debug 1 0 2019-12-15 20:52:15.306
!MESSAGE DS_ERROR: Error connecting to the target:
(Error -614 @ 0x0)
The target indicates there is an error condition from a previous SWD 
request. Clear the error the condition, and try the SWD request again.
(Emulation package 8.3.0.00003)


!ENTRY com.ti.ccstudio.debug 1 0 2019-12-15 20:52:19.032
!MESSAGE DS_ERROR: CS_DAP_0: Error connecting to the target: (Error -614 @ 0x0) The target indicates there is an error condition from a previous SWD  request. Clear the error the condition, and try the SWD request again. (Emulation package 8.3.0.00003) 


!ENTRY com.ti.ccstudio.debug 1 0 2019-12-15 20:52:19.063
!MESSAGE DS_ERROR: Error connecting to the target:
(Error -614 @ 0x0)
The target indicates there is an error condition from a previous SWD 
request. Clear the error the condition, and try the SWD request again.
(Emulation package 8.3.0.00003)


!ENTRY com.ti.ccstudio.debug 1 0 2019-12-15 20:52:21.204
!MESSAGE DS_ERROR: CS_DAP_0: Error connecting to the target: (Error -614 @ 0x0) The target indicates there is an error condition from a previous SWD  request. Clear the error the condition, and try the SWD request again. (Emulation package 8.3.0.00003) 


!ENTRY com.ti.ccstudio.debug 1 0 2019-12-15 20:52:21.235
!MESSAGE DS_ERROR: Error connecting to the target:
(Error -614 @ 0x0)
The target indicates there is an error condition from a previous SWD 
request. Clear the error the condition, and try the SWD request again.
(Emulation package 8.3.0.00003)


!ENTRY com.ti.ccstudio.debug 1 0 2019-12-15 20:52:59.198
!MESSAGE DS_ERROR: CORTEX_M4_0: JTAG Communication Error: (Error -613 @ 0x0) The target indicates that it is busy.  Either try the SWD request  again, or abort the transaction. (Emulation package 8.3.0.00003) 


!ENTRY com.ti.ccstudio.debug 1 0 2019-12-15 20:52:59.276
!MESSAGE DS_ERROR: CORTEX_M4_0: Failed to remove the debug state from the target before disconnecting.  There may still be breakpoint op-codes embedded in program memory.  It is recommended that you reset the emulator before you connect and reload your program before you continue debugging


!ENTRY com.ti.ccstudio.debug 4 0 2019-12-15 20:54:07.838
!MESSAGE An internal error was logged by 'com.ti.ccstudio.debug'.
!STACK 0
java.util.concurrent.ExecutionException: org.json.JSONException: Module Closed
	at java.util.concurrent.CompletableFuture.reportGet(Unknown Source)
	at java.util.concurrent.CompletableFuture.get(Unknown Source)
	at com.ti.ccstudio.debug.service.ApplicationService.getConnectedDebugProbes(ApplicationService.java:295)
	at com.ti.ccstudio.debug.service.ApplicationService.detectXDS110ConnectedProbes(ApplicationService.java:356)
	at com.ti.ccstudio.debug.service.ApplicationService.initDebugger(ApplicationService.java:418)
	at com.ti.ccstudio.debug.service.ApplicationService.access$0(ApplicationService.java:408)
	at com.ti.ccstudio.debug.service.ApplicationService$ThreadContextCache.retrieve(ApplicationService.java:136)
	at com.ti.ccstudio.debug.dsf.extensions.concurrent.DataCache.wait(DataCache.java:59)
	at com.ti.ccstudio.debug.service.ApplicationService.getCpuBeingDebugged(ApplicationService.java:1057)
	at com.ti.ccstudio.debug.launch.CCSLaunchDelegate$2.execute(CCSLaunchDelegate.java:139)
	at org.eclipse.cdt.dsf.concurrent.Query.run(Query.java:177)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: org.json.JSONException: Module Closed
	at com.ti.cloudagent.communication.JSONInterface.call(JSONInterface.java:54)
	at com.ti.cloudagent.Agent.createModule(Agent.java:171)
	at com.ti.cloudagent.Agent.lambda$createSpecificModule$4(Agent.java:96)
	at java.util.concurrent.CompletableFuture.uniHandle(Unknown Source)
	at java.util.concurrent.CompletableFuture.uniHandleStage(Unknown Source)
	at java.util.concurrent.CompletableFuture.handle(Unknown Source)
	at com.ti.cloudagent.Agent.createSpecificModule(Agent.java:87)
	at com.ti.cloudagent.Agent.createDeviceDetector(Agent.java:76)
	... 16 more

!ENTRY com.ti.ccstudio.debug 4 0 2019-12-15 20:54:33.076
!MESSAGE An internal error was logged by 'com.ti.ccstudio.debug'.
!STACK 0
java.util.concurrent.ExecutionException: org.json.JSONException: Module Closed
	at java.util.concurrent.CompletableFuture.reportGet(Unknown Source)
	at java.util.concurrent.CompletableFuture.get(Unknown Source)
	at com.ti.ccstudio.debug.service.ApplicationService.getConnectedDebugProbes(ApplicationService.java:295)
	at com.ti.ccstudio.debug.service.ApplicationService.detectXDS110ConnectedProbes(ApplicationService.java:356)
	at com.ti.ccstudio.debug.service.ApplicationService.initDebugger(ApplicationService.java:418)
	at com.ti.ccstudio.debug.service.ApplicationService.access$0(ApplicationService.java:408)
	at com.ti.ccstudio.debug.service.ApplicationService$ThreadContextCache.retrieve(ApplicationService.java:136)
	at com.ti.ccstudio.debug.dsf.extensions.concurrent.DataCache.wait(DataCache.java:59)
	at com.ti.ccstudio.debug.service.ApplicationService.getCpuBeingDebugged(ApplicationService.java:1057)
	at com.ti.ccstudio.debug.launch.CCSLaunchDelegate$2.execute(CCSLaunchDelegate.java:139)
	at org.eclipse.cdt.dsf.concurrent.Query.run(Query.java:177)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: org.json.JSONException: Module Closed
	at com.ti.cloudagent.communication.JSONInterface.call(JSONInterface.java:54)
	at com.ti.cloudagent.Agent.createModule(Agent.java:171)
	at com.ti.cloudagent.Agent.lambda$createSpecificModule$4(Agent.java:96)
	at java.util.concurrent.CompletableFuture.uniHandle(Unknown Source)
	at java.util.concurrent.CompletableFuture.uniHandleStage(Unknown Source)
	at java.util.concurrent.CompletableFuture.handle(Unknown Source)
	at com.ti.cloudagent.Agent.createSpecificModule(Agent.java:87)
	at com.ti.cloudagent.Agent.createDeviceDetector(Agent.java:76)
	... 16 more

!ENTRY com.ti.ccstudio.debug 1 0 2019-12-15 20:54:48.538
!MESSAGE DS_ERROR: CORTEX_M4_0: JTAG Communication Error: (Error -261 @ 0x0) Invalid response was received from the XDS110. (Emulation package 8.3.0.00003) 


!ENTRY com.ti.ccstudio.debug 1 0 2019-12-15 20:54:48.583
!MESSAGE DS_ERROR: CORTEX_M4_0: Failed to remove the debug state from the target before disconnecting.  There may still be breakpoint op-codes embedded in program memory.  It is recommended that you reset the emulator before you connect and reload your program before you continue debugging


!ENTRY com.ti.ccstudio.debug 4 0 2019-12-15 20:57:43.316
!MESSAGE An internal error was logged by 'com.ti.ccstudio.debug'.
!STACK 0
java.util.concurrent.ExecutionException: org.json.JSONException: Module Closed
	at java.util.concurrent.CompletableFuture.reportGet(Unknown Source)
	at java.util.concurrent.CompletableFuture.get(Unknown Source)
	at com.ti.ccstudio.debug.service.ApplicationService.getConnectedDebugProbes(ApplicationService.java:295)
	at com.ti.ccstudio.debug.service.ApplicationService.detectXDS110ConnectedProbes(ApplicationService.java:356)
	at com.ti.ccstudio.debug.service.ApplicationService.initDebugger(ApplicationService.java:418)
	at com.ti.ccstudio.debug.service.ApplicationService.access$0(ApplicationService.java:408)
	at com.ti.ccstudio.debug.service.ApplicationService$ThreadContextCache.retrieve(ApplicationService.java:136)
	at com.ti.ccstudio.debug.dsf.extensions.concurrent.DataCache.wait(DataCache.java:59)
	at com.ti.ccstudio.debug.service.ApplicationService.getCpuBeingDebugged(ApplicationService.java:1057)
	at com.ti.ccstudio.debug.launch.CCSLaunchDelegate$2.execute(CCSLaunchDelegate.java:139)
	at org.eclipse.cdt.dsf.concurrent.Query.run(Query.java:177)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: org.json.JSONException: Module Closed
	at com.ti.cloudagent.communication.JSONInterface.call(JSONInterface.java:54)
	at com.ti.cloudagent.Agent.createModule(Agent.java:171)
	at com.ti.cloudagent.Agent.lambda$createSpecificModule$4(Agent.java:96)
	at java.util.concurrent.CompletableFuture.uniHandle(Unknown Source)
	at java.util.concurrent.CompletableFuture.uniHandleStage(Unknown Source)
	at java.util.concurrent.CompletableFuture.handle(Unknown Source)
	at com.ti.cloudagent.Agent.createSpecificModule(Agent.java:87)
	at com.ti.cloudagent.Agent.createDeviceDetector(Agent.java:76)
	... 16 more

!ENTRY com.ti.ccstudio.debug 1 0 2019-12-15 20:57:59.543
!MESSAGE DS_ERROR: CORTEX_M4_0: JTAG Communication Error: (Error -261 @ 0x0) Invalid response was received from the XDS110. (Emulation package 8.3.0.00003) 


!ENTRY com.ti.ccstudio.debug 1 0 2019-12-15 20:57:59.613
!MESSAGE DS_ERROR: CORTEX_M4_0: Failed to remove the debug state from the target before disconnecting.  There may still be breakpoint op-codes embedded in program memory.  It is recommended that you reset the emulator before you connect and reload your program before you continue debugging


!ENTRY com.ti.ccstudio.debug 4 0 2019-12-15 20:59:30.316
!MESSAGE An internal error was logged by 'com.ti.ccstudio.debug'.
!STACK 0
java.util.concurrent.ExecutionException: org.json.JSONException: Module Closed
	at java.util.concurrent.CompletableFuture.reportGet(Unknown Source)
	at java.util.concurrent.CompletableFuture.get(Unknown Source)
	at com.ti.ccstudio.debug.service.ApplicationService.getConnectedDebugProbes(ApplicationService.java:295)
	at com.ti.ccstudio.debug.service.ApplicationService.detectXDS110ConnectedProbes(ApplicationService.java:356)
	at com.ti.ccstudio.debug.service.ApplicationService.initDebugger(ApplicationService.java:418)
	at com.ti.ccstudio.debug.service.ApplicationService.access$0(ApplicationService.java:408)
	at com.ti.ccstudio.debug.service.ApplicationService$ThreadContextCache.retrieve(ApplicationService.java:136)
	at com.ti.ccstudio.debug.dsf.extensions.concurrent.DataCache.wait(DataCache.java:59)
	at com.ti.ccstudio.debug.service.ApplicationService.getCpuBeingDebugged(ApplicationService.java:1057)
	at com.ti.ccstudio.debug.launch.CCSLaunchDelegate$2.execute(CCSLaunchDelegate.java:139)
	at org.eclipse.cdt.dsf.concurrent.Query.run(Query.java:177)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: org.json.JSONException: Module Closed
	at com.ti.cloudagent.communication.JSONInterface.call(JSONInterface.java:54)
	at com.ti.cloudagent.Agent.createModule(Agent.java:171)
	at com.ti.cloudagent.Agent.lambda$createSpecificModule$4(Agent.java:96)
	at java.util.concurrent.CompletableFuture.uniHandle(Unknown Source)
	at java.util.concurrent.CompletableFuture.uniHandleStage(Unknown Source)
	at java.util.concurrent.CompletableFuture.handle(Unknown Source)
	at com.ti.cloudagent.Agent.createSpecificModule(Agent.java:87)
	at com.ti.cloudagent.Agent.createDeviceDetector(Agent.java:76)
	... 16 more

!ENTRY com.ti.ccstudio.debug 1 0 2019-12-15 20:59:40.619
!MESSAGE DS_ERROR: CORTEX_M4_0: JTAG Communication Error: (Error -261 @ 0x0) Invalid response was received from the XDS110. (Emulation package 8.3.0.00003) 


!ENTRY com.ti.ccstudio.debug 1 0 2019-12-15 20:59:40.641
!MESSAGE DS_ERROR: CORTEX_M4_0: Failed to remove the debug state from the target before disconnecting.  There may still be breakpoint op-codes embedded in program memory.  It is recommended that you reset the emulator before you connect and reload your program before you continue debugging


!ENTRY com.ti.ccstudio.debug 4 0 2019-12-15 21:00:29.465
!MESSAGE An internal error was logged by 'com.ti.ccstudio.debug'.
!STACK 0
java.util.concurrent.ExecutionException: org.json.JSONException: Module Closed
	at java.util.concurrent.CompletableFuture.reportGet(Unknown Source)
	at java.util.concurrent.CompletableFuture.get(Unknown Source)
	at com.ti.ccstudio.debug.service.ApplicationService.getConnectedDebugProbes(ApplicationService.java:295)
	at com.ti.ccstudio.debug.service.ApplicationService.detectXDS110ConnectedProbes(ApplicationService.java:356)
	at com.ti.ccstudio.debug.service.ApplicationService.initDebugger(ApplicationService.java:418)
	at com.ti.ccstudio.debug.service.ApplicationService.access$0(ApplicationService.java:408)
	at com.ti.ccstudio.debug.service.ApplicationService$ThreadContextCache.retrieve(ApplicationService.java:136)
	at com.ti.ccstudio.debug.dsf.extensions.concurrent.DataCache.wait(DataCache.java:59)
	at com.ti.ccstudio.debug.service.ApplicationService.getCpuBeingDebugged(ApplicationService.java:1057)
	at com.ti.ccstudio.debug.launch.CCSLaunchDelegate$2.execute(CCSLaunchDelegate.java:139)
	at org.eclipse.cdt.dsf.concurrent.Query.run(Query.java:177)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: org.json.JSONException: Module Closed
	at com.ti.cloudagent.communication.JSONInterface.call(JSONInterface.java:54)
	at com.ti.cloudagent.Agent.createModule(Agent.java:171)
	at com.ti.cloudagent.Agent.lambda$createSpecificModule$4(Agent.java:96)
	at java.util.concurrent.CompletableFuture.uniHandle(Unknown Source)
	at java.util.concurrent.CompletableFuture.uniHandleStage(Unknown Source)
	at java.util.concurrent.CompletableFuture.handle(Unknown Source)
	at com.ti.cloudagent.Agent.createSpecificModule(Agent.java:87)
	at com.ti.cloudagent.Agent.createDeviceDetector(Agent.java:76)
	... 16 more

!ENTRY com.ti.ccstudio.debug 1 0 2019-12-15 21:00:29.684
!MESSAGE DS_ERROR: CS_DAP_0: Error connecting to the target: (Error -261 @ 0x0) Invalid response was received from the XDS110. (Emulation package 8.3.0.00003) 


!ENTRY com.ti.ccstudio.debug 1 0 2019-12-15 21:00:30.112
!MESSAGE DS_ERROR: Error connecting to the target:
(Error -261 @ 0x0)
Invalid response was received from the XDS110.
(Emulation package 8.3.0.00003)


!ENTRY com.ti.ccstudio.debug 1 0 2019-12-15 21:00:49.514
!MESSAGE DS_ERROR: CORTEX_M4_0: JTAG Communication Error: (Error -261 @ 0x0) Invalid response was received from the XDS110. (Emulation package 8.3.0.00003) 


!ENTRY com.ti.ccstudio.debug 1 0 2019-12-15 21:00:49.584
!MESSAGE DS_ERROR: CORTEX_M4_0: Failed to remove the debug state from the target before disconnecting.  There may still be breakpoint op-codes embedded in program memory.  It is recommended that you reset the emulator before you connect and reload your program before you continue debugging


!ENTRY com.ti.ccstudio.debug 4 0 2019-12-15 21:02:41.545
!MESSAGE An internal error was logged by 'com.ti.ccstudio.debug'.
!STACK 0
java.util.concurrent.ExecutionException: org.json.JSONException: Module Closed
	at java.util.concurrent.CompletableFuture.reportGet(Unknown Source)
	at java.util.concurrent.CompletableFuture.get(Unknown Source)
	at com.ti.ccstudio.debug.service.ApplicationService.getConnectedDebugProbes(ApplicationService.java:295)
	at com.ti.ccstudio.debug.service.ApplicationService.detectXDS110ConnectedProbes(ApplicationService.java:356)
	at com.ti.ccstudio.debug.service.ApplicationService.initDebugger(ApplicationService.java:418)
	at com.ti.ccstudio.debug.service.ApplicationService.access$0(ApplicationService.java:408)
	at com.ti.ccstudio.debug.service.ApplicationService$ThreadContextCache.retrieve(ApplicationService.java:136)
	at com.ti.ccstudio.debug.dsf.extensions.concurrent.DataCache.wait(DataCache.java:59)
	at com.ti.ccstudio.debug.service.ApplicationService.getCpuBeingDebugged(ApplicationService.java:1057)
	at com.ti.ccstudio.debug.launch.CCSLaunchDelegate$2.execute(CCSLaunchDelegate.java:139)
	at org.eclipse.cdt.dsf.concurrent.Query.run(Query.java:177)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: org.json.JSONException: Module Closed
	at com.ti.cloudagent.communication.JSONInterface.call(JSONInterface.java:54)
	at com.ti.cloudagent.Agent.createModule(Agent.java:171)
	at com.ti.cloudagent.Agent.lambda$createSpecificModule$4(Agent.java:96)
	at java.util.concurrent.CompletableFuture.uniHandle(Unknown Source)
	at java.util.concurrent.CompletableFuture.uniHandleStage(Unknown Source)
	at java.util.concurrent.CompletableFuture.handle(Unknown Source)
	at com.ti.cloudagent.Agent.createSpecificModule(Agent.java:87)
	at com.ti.cloudagent.Agent.createDeviceDetector(Agent.java:76)
	... 16 more

!ENTRY com.ti.ccstudio.debug 1 0 2019-12-15 21:02:54.198
!MESSAGE DS_ERROR: CORTEX_M4_0: JTAG Communication Error: (Error -261 @ 0x0) Invalid response was received from the XDS110. (Emulation package 8.3.0.00003) 


!ENTRY com.ti.ccstudio.debug 1 0 2019-12-15 21:02:54.237
!MESSAGE DS_ERROR: CORTEX_M4_0: Failed to remove the debug state from the target before disconnecting.  There may still be breakpoint op-codes embedded in program memory.  It is recommended that you reset the emulator before you connect and reload your program before you continue debugging


!ENTRY com.ti.ccstudio.debug 4 0 2019-12-15 21:08:12.479
!MESSAGE An internal error was logged by 'com.ti.ccstudio.debug'.
!STACK 0
java.util.concurrent.ExecutionException: org.json.JSONException: Module Closed
	at java.util.concurrent.CompletableFuture.reportGet(Unknown Source)
	at java.util.concurrent.CompletableFuture.get(Unknown Source)
	at com.ti.ccstudio.debug.service.ApplicationService.getConnectedDebugProbes(ApplicationService.java:295)
	at com.ti.ccstudio.debug.service.ApplicationService.detectXDS110ConnectedProbes(ApplicationService.java:356)
	at com.ti.ccstudio.debug.service.ApplicationService.initDebugger(ApplicationService.java:418)
	at com.ti.ccstudio.debug.service.ApplicationService.access$0(ApplicationService.java:408)
	at com.ti.ccstudio.debug.service.ApplicationService$ThreadContextCache.retrieve(ApplicationService.java:136)
	at com.ti.ccstudio.debug.dsf.extensions.concurrent.DataCache.wait(DataCache.java:59)
	at com.ti.ccstudio.debug.service.ApplicationService.getCpuBeingDebugged(ApplicationService.java:1057)
	at com.ti.ccstudio.debug.launch.CCSLaunchDelegate$2.execute(CCSLaunchDelegate.java:139)
	at org.eclipse.cdt.dsf.concurrent.Query.run(Query.java:177)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: org.json.JSONException: Module Closed
	at com.ti.cloudagent.communication.JSONInterface.call(JSONInterface.java:54)
	at com.ti.cloudagent.Agent.createModule(Agent.java:171)
	at com.ti.cloudagent.Agent.lambda$createSpecificModule$4(Agent.java:96)
	at java.util.concurrent.CompletableFuture.uniHandle(Unknown Source)
	at java.util.concurrent.CompletableFuture.uniHandleStage(Unknown Source)
	at java.util.concurrent.CompletableFuture.handle(Unknown Source)
	at com.ti.cloudagent.Agent.createSpecificModule(Agent.java:87)
	at com.ti.cloudagent.Agent.createDeviceDetector(Agent.java:76)
	... 16 more

!ENTRY com.ti.ccstudio.debug 4 0 2019-12-15 21:09:07.115
!MESSAGE An internal error was logged by 'com.ti.ccstudio.debug'.
!STACK 0
java.util.concurrent.ExecutionException: org.json.JSONException: Module Closed
	at java.util.concurrent.CompletableFuture.reportGet(Unknown Source)
	at java.util.concurrent.CompletableFuture.get(Unknown Source)
	at com.ti.ccstudio.debug.service.ApplicationService.getConnectedDebugProbes(ApplicationService.java:295)
	at com.ti.ccstudio.debug.service.ApplicationService.detectXDS110ConnectedProbes(ApplicationService.java:356)
	at com.ti.ccstudio.debug.service.ApplicationService.initDebugger(ApplicationService.java:418)
	at com.ti.ccstudio.debug.service.ApplicationService.access$0(ApplicationService.java:408)
	at com.ti.ccstudio.debug.service.ApplicationService$ThreadContextCache.retrieve(ApplicationService.java:136)
	at com.ti.ccstudio.debug.dsf.extensions.concurrent.DataCache.wait(DataCache.java:59)
	at com.ti.ccstudio.debug.service.ApplicationService.getCpuBeingDebugged(ApplicationService.java:1057)
	at com.ti.ccstudio.debug.launch.CCSLaunchDelegate$2.execute(CCSLaunchDelegate.java:139)
	at org.eclipse.cdt.dsf.concurrent.Query.run(Query.java:177)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: org.json.JSONException: Module Closed
	at com.ti.cloudagent.communication.JSONInterface.call(JSONInterface.java:54)
	at com.ti.cloudagent.Agent.createModule(Agent.java:171)
	at com.ti.cloudagent.Agent.lambda$createSpecificModule$4(Agent.java:96)
	at java.util.concurrent.CompletableFuture.uniHandle(Unknown Source)
	at java.util.concurrent.CompletableFuture.uniHandleStage(Unknown Source)
	at java.util.concurrent.CompletableFuture.handle(Unknown Source)
	at com.ti.cloudagent.Agent.createSpecificModule(Agent.java:87)
	at com.ti.cloudagent.Agent.createDeviceDetector(Agent.java:76)
	... 16 more

!ENTRY com.ti.ccstudio.debug 4 0 2019-12-15 21:09:34.848
!MESSAGE An internal error was logged by 'com.ti.ccstudio.debug'.
!STACK 0
java.util.concurrent.ExecutionException: org.json.JSONException: Module Closed
	at java.util.concurrent.CompletableFuture.reportGet(Unknown Source)
	at java.util.concurrent.CompletableFuture.get(Unknown Source)
	at com.ti.ccstudio.debug.service.ApplicationService.getConnectedDebugProbes(ApplicationService.java:295)
	at com.ti.ccstudio.debug.service.ApplicationService.detectXDS110ConnectedProbes(ApplicationService.java:356)
	at com.ti.ccstudio.debug.service.ApplicationService.initDebugger(ApplicationService.java:418)
	at com.ti.ccstudio.debug.service.ApplicationService.access$0(ApplicationService.java:408)
	at com.ti.ccstudio.debug.service.ApplicationService$ThreadContextCache.retrieve(ApplicationService.java:136)
	at com.ti.ccstudio.debug.dsf.extensions.concurrent.DataCache.wait(DataCache.java:59)
	at com.ti.ccstudio.debug.service.ApplicationService.getCpuBeingDebugged(ApplicationService.java:1057)
	at com.ti.ccstudio.debug.launch.CCSLaunchDelegate$2.execute(CCSLaunchDelegate.java:139)
	at org.eclipse.cdt.dsf.concurrent.Query.run(Query.java:177)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: org.json.JSONException: Module Closed
	at com.ti.cloudagent.communication.JSONInterface.call(JSONInterface.java:54)
	at com.ti.cloudagent.Agent.createModule(Agent.java:171)
	at com.ti.cloudagent.Agent.lambda$createSpecificModule$4(Agent.java:96)
	at java.util.concurrent.CompletableFuture.uniHandle(Unknown Source)
	at java.util.concurrent.CompletableFuture.uniHandleStage(Unknown Source)
	at java.util.concurrent.CompletableFuture.handle(Unknown Source)
	at com.ti.cloudagent.Agent.createSpecificModule(Agent.java:87)
	at com.ti.cloudagent.Agent.createDeviceDetector(Agent.java:76)
	... 16 more

!ENTRY com.ti.ccstudio.debug 4 0 2019-12-15 21:10:34.751
!MESSAGE An internal error was logged by 'com.ti.ccstudio.debug'.
!STACK 0
java.util.concurrent.ExecutionException: org.json.JSONException: Module Closed
	at java.util.concurrent.CompletableFuture.reportGet(Unknown Source)
	at java.util.concurrent.CompletableFuture.get(Unknown Source)
	at com.ti.ccstudio.debug.service.ApplicationService.getConnectedDebugProbes(ApplicationService.java:295)
	at com.ti.ccstudio.debug.service.ApplicationService.detectXDS110ConnectedProbes(ApplicationService.java:356)
	at com.ti.ccstudio.debug.service.ApplicationService.initDebugger(ApplicationService.java:418)
	at com.ti.ccstudio.debug.service.ApplicationService.access$0(ApplicationService.java:408)
	at com.ti.ccstudio.debug.service.ApplicationService$ThreadContextCache.retrieve(ApplicationService.java:136)
	at com.ti.ccstudio.debug.dsf.extensions.concurrent.DataCache.wait(DataCache.java:59)
	at com.ti.ccstudio.debug.service.ApplicationService.getCpuBeingDebugged(ApplicationService.java:1057)
	at com.ti.ccstudio.debug.launch.CCSLaunchDelegate$2.execute(CCSLaunchDelegate.java:139)
	at org.eclipse.cdt.dsf.concurrent.Query.run(Query.java:177)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: org.json.JSONException: Module Closed
	at com.ti.cloudagent.communication.JSONInterface.call(JSONInterface.java:54)
	at com.ti.cloudagent.Agent.createModule(Agent.java:171)
	at com.ti.cloudagent.Agent.lambda$createSpecificModule$4(Agent.java:96)
	at java.util.concurrent.CompletableFuture.uniHandle(Unknown Source)
	at java.util.concurrent.CompletableFuture.uniHandleStage(Unknown Source)
	at java.util.concurrent.CompletableFuture.handle(Unknown Source)
	at com.ti.cloudagent.Agent.createSpecificModule(Agent.java:87)
	at com.ti.cloudagent.Agent.createDeviceDetector(Agent.java:76)
	... 16 more

!ENTRY com.ti.ccstudio.debug 1 0 2019-12-15 21:10:44.681
!MESSAGE DS_ERROR: CORTEX_M4_0: JTAG Communication Error: (Error -261 @ 0x0) Invalid response was received from the XDS110. (Emulation package 8.3.0.00003) 


!ENTRY com.ti.ccstudio.debug 1 0 2019-12-15 21:10:44.728
!MESSAGE DS_ERROR: CORTEX_M4_0: Failed to remove the debug state from the target before disconnecting.  There may still be breakpoint op-codes embedded in program memory.  It is recommended that you reset the emulator before you connect and reload your program before you continue debugging


!ENTRY com.ti.ccstudio.debug 4 0 2019-12-15 21:11:51.098
!MESSAGE An internal error was logged by 'com.ti.ccstudio.debug'.
!STACK 0
java.util.concurrent.ExecutionException: org.json.JSONException: Module Closed
	at java.util.concurrent.CompletableFuture.reportGet(Unknown Source)
	at java.util.concurrent.CompletableFuture.get(Unknown Source)
	at com.ti.ccstudio.debug.service.ApplicationService.getConnectedDebugProbes(ApplicationService.java:295)
	at com.ti.ccstudio.debug.service.ApplicationService.detectXDS110ConnectedProbes(ApplicationService.java:356)
	at com.ti.ccstudio.debug.service.ApplicationService.initDebugger(ApplicationService.java:418)
	at com.ti.ccstudio.debug.service.ApplicationService.access$0(ApplicationService.java:408)
	at com.ti.ccstudio.debug.service.ApplicationService$ThreadContextCache.retrieve(ApplicationService.java:136)
	at com.ti.ccstudio.debug.dsf.extensions.concurrent.DataCache.wait(DataCache.java:59)
	at com.ti.ccstudio.debug.service.ApplicationService.getCpuBeingDebugged(ApplicationService.java:1057)
	at com.ti.ccstudio.debug.launch.CCSLaunchDelegate$2.execute(CCSLaunchDelegate.java:139)
	at org.eclipse.cdt.dsf.concurrent.Query.run(Query.java:177)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: org.json.JSONException: Module Closed
	at com.ti.cloudagent.communication.JSONInterface.call(JSONInterface.java:54)
	at com.ti.cloudagent.Agent.createModule(Agent.java:171)
	at com.ti.cloudagent.Agent.lambda$createSpecificModule$4(Agent.java:96)
	at java.util.concurrent.CompletableFuture.uniHandle(Unknown Source)
	at java.util.concurrent.CompletableFuture.uniHandleStage(Unknown Source)
	at java.util.concurrent.CompletableFuture.handle(Unknown Source)
	at com.ti.cloudagent.Agent.createSpecificModule(Agent.java:87)
	at com.ti.cloudagent.Agent.createDeviceDetector(Agent.java:76)
	... 16 more

!ENTRY com.ti.ccstudio.debug 4 0 2019-12-15 21:12:39.161
!MESSAGE An internal error was logged by 'com.ti.ccstudio.debug'.
!STACK 0
java.util.concurrent.ExecutionException: org.json.JSONException: Module Closed
	at java.util.concurrent.CompletableFuture.reportGet(Unknown Source)
	at java.util.concurrent.CompletableFuture.get(Unknown Source)
	at com.ti.ccstudio.debug.service.ApplicationService.getConnectedDebugProbes(ApplicationService.java:295)
	at com.ti.ccstudio.debug.service.ApplicationService.detectXDS110ConnectedProbes(ApplicationService.java:356)
	at com.ti.ccstudio.debug.service.ApplicationService.initDebugger(ApplicationService.java:418)
	at com.ti.ccstudio.debug.service.ApplicationService.access$0(ApplicationService.java:408)
	at com.ti.ccstudio.debug.service.ApplicationService$ThreadContextCache.retrieve(ApplicationService.java:136)
	at com.ti.ccstudio.debug.dsf.extensions.concurrent.DataCache.wait(DataCache.java:59)
	at com.ti.ccstudio.debug.service.ApplicationService.getCpuBeingDebugged(ApplicationService.java:1057)
	at com.ti.ccstudio.debug.launch.CCSLaunchDelegate$2.execute(CCSLaunchDelegate.java:139)
	at org.eclipse.cdt.dsf.concurrent.Query.run(Query.java:177)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: org.json.JSONException: Module Closed
	at com.ti.cloudagent.communication.JSONInterface.call(JSONInterface.java:54)
	at com.ti.cloudagent.Agent.createModule(Agent.java:171)
	at com.ti.cloudagent.Agent.lambda$createSpecificModule$4(Agent.java:96)
	at java.util.concurrent.CompletableFuture.uniHandle(Unknown Source)
	at java.util.concurrent.CompletableFuture.uniHandleStage(Unknown Source)
	at java.util.concurrent.CompletableFuture.handle(Unknown Source)
	at com.ti.cloudagent.Agent.createSpecificModule(Agent.java:87)
	at com.ti.cloudagent.Agent.createDeviceDetector(Agent.java:76)
	... 16 more

!ENTRY com.ti.ccstudio.debug 1 0 2019-12-15 21:12:51.184
!MESSAGE DS_ERROR: CORTEX_M4_0: JTAG Communication Error: (Error -261 @ 0x0) Invalid response was received from the XDS110. (Emulation package 8.3.0.00003) 


!ENTRY com.ti.ccstudio.debug 1 0 2019-12-15 21:12:51.218
!MESSAGE DS_ERROR: CORTEX_M4_0: Failed to remove the debug state from the target before disconnecting.  There may still be breakpoint op-codes embedded in program memory.  It is recommended that you reset the emulator before you connect and reload your program before you continue debugging


!ENTRY com.ti.ccstudio.debug 4 0 2019-12-15 21:13:40.406
!MESSAGE An internal error was logged by 'com.ti.ccstudio.debug'.
!STACK 0
java.util.concurrent.ExecutionException: org.json.JSONException: Module Closed
	at java.util.concurrent.CompletableFuture.reportGet(Unknown Source)
	at java.util.concurrent.CompletableFuture.get(Unknown Source)
	at com.ti.ccstudio.debug.service.ApplicationService.getConnectedDebugProbes(ApplicationService.java:295)
	at com.ti.ccstudio.debug.service.ApplicationService.detectXDS110ConnectedProbes(ApplicationService.java:356)
	at com.ti.ccstudio.debug.service.ApplicationService.initDebugger(ApplicationService.java:418)
	at com.ti.ccstudio.debug.service.ApplicationService.access$0(ApplicationService.java:408)
	at com.ti.ccstudio.debug.service.ApplicationService$ThreadContextCache.retrieve(ApplicationService.java:136)
	at com.ti.ccstudio.debug.dsf.extensions.concurrent.DataCache.wait(DataCache.java:59)
	at com.ti.ccstudio.debug.service.ApplicationService.getCpuBeingDebugged(ApplicationService.java:1057)
	at com.ti.ccstudio.debug.launch.CCSLaunchDelegate$2.execute(CCSLaunchDelegate.java:139)
	at org.eclipse.cdt.dsf.concurrent.Query.run(Query.java:177)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: org.json.JSONException: Module Closed
	at com.ti.cloudagent.communication.JSONInterface.call(JSONInterface.java:54)
	at com.ti.cloudagent.Agent.createModule(Agent.java:171)
	at com.ti.cloudagent.Agent.lambda$createSpecificModule$4(Agent.java:96)
	at java.util.concurrent.CompletableFuture.uniHandle(Unknown Source)
	at java.util.concurrent.CompletableFuture.uniHandleStage(Unknown Source)
	at java.util.concurrent.CompletableFuture.handle(Unknown Source)
	at com.ti.cloudagent.Agent.createSpecificModule(Agent.java:87)
	at com.ti.cloudagent.Agent.createDeviceDetector(Agent.java:76)
	... 16 more

!ENTRY com.ti.ccstudio.debug 1 0 2019-12-15 21:14:03.763
!MESSAGE DS_ERROR: CORTEX_M4_0: JTAG Communication Error: (Error -261 @ 0x0) Invalid response was received from the XDS110. (Emulation package 8.3.0.00003) 


!ENTRY com.ti.ccstudio.debug 1 0 2019-12-15 21:14:03.818
!MESSAGE DS_ERROR: CORTEX_M4_0: Failed to remove the debug state from the target before disconnecting.  There may still be breakpoint op-codes embedded in program memory.  It is recommended that you reset the emulator before you connect and reload your program before you continue debugging


!ENTRY com.ti.ccstudio.debug 4 0 2019-12-15 21:14:45.135
!MESSAGE An internal error was logged by 'com.ti.ccstudio.debug'.
!STACK 0
java.util.concurrent.ExecutionException: org.json.JSONException: Module Closed
	at java.util.concurrent.CompletableFuture.reportGet(Unknown Source)
	at java.util.concurrent.CompletableFuture.get(Unknown Source)
	at com.ti.ccstudio.debug.service.ApplicationService.getConnectedDebugProbes(ApplicationService.java:295)
	at com.ti.ccstudio.debug.service.ApplicationService.detectXDS110ConnectedProbes(ApplicationService.java:356)
	at com.ti.ccstudio.debug.service.ApplicationService.initDebugger(ApplicationService.java:418)
	at com.ti.ccstudio.debug.service.ApplicationService.access$0(ApplicationService.java:408)
	at com.ti.ccstudio.debug.service.ApplicationService$ThreadContextCache.retrieve(ApplicationService.java:136)
	at com.ti.ccstudio.debug.dsf.extensions.concurrent.DataCache.wait(DataCache.java:59)
	at com.ti.ccstudio.debug.service.ApplicationService.getCpuBeingDebugged(ApplicationService.java:1057)
	at com.ti.ccstudio.debug.launch.CCSLaunchDelegate$2.execute(CCSLaunchDelegate.java:139)
	at org.eclipse.cdt.dsf.concurrent.Query.run(Query.java:177)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: org.json.JSONException: Module Closed
	at com.ti.cloudagent.communication.JSONInterface.call(JSONInterface.java:54)
	at com.ti.cloudagent.Agent.createModule(Agent.java:171)
	at com.ti.cloudagent.Agent.lambda$createSpecificModule$4(Agent.java:96)
	at java.util.concurrent.CompletableFuture.uniHandle(Unknown Source)
	at java.util.concurrent.CompletableFuture.uniHandleStage(Unknown Source)
	at java.util.concurrent.CompletableFuture.handle(Unknown Source)
	at com.ti.cloudagent.Agent.createSpecificModule(Agent.java:87)
	at com.ti.cloudagent.Agent.createDeviceDetector(Agent.java:76)
	... 16 more

!ENTRY com.ti.ccstudio.debug 1 0 2019-12-15 21:14:54.205
!MESSAGE DS_ERROR: CORTEX_M4_0: JTAG Communication Error: (Error -261 @ 0x0) Invalid response was received from the XDS110. (Emulation package 8.3.0.00003) 


!ENTRY com.ti.ccstudio.debug 1 0 2019-12-15 21:14:54.246
!MESSAGE DS_ERROR: CORTEX_M4_0: Failed to remove the debug state from the target before disconnecting.  There may still be breakpoint op-codes embedded in program memory.  It is recommended that you reset the emulator before you connect and reload your program before you continue debugging


!ENTRY com.ti.ccstudio.debug 4 0 2019-12-15 21:16:51.540
!MESSAGE An internal error was logged by 'com.ti.ccstudio.debug'.
!STACK 0
java.util.concurrent.ExecutionException: org.json.JSONException: Module Closed
	at java.util.concurrent.CompletableFuture.reportGet(Unknown Source)
	at java.util.concurrent.CompletableFuture.get(Unknown Source)
	at com.ti.ccstudio.debug.service.ApplicationService.getConnectedDebugProbes(ApplicationService.java:295)
	at com.ti.ccstudio.debug.service.ApplicationService.detectXDS110ConnectedProbes(ApplicationService.java:356)
	at com.ti.ccstudio.debug.service.ApplicationService.initDebugger(ApplicationService.java:418)
	at com.ti.ccstudio.debug.service.ApplicationService.access$0(ApplicationService.java:408)
	at com.ti.ccstudio.debug.service.ApplicationService$ThreadContextCache.retrieve(ApplicationService.java:136)
	at com.ti.ccstudio.debug.dsf.extensions.concurrent.DataCache.wait(DataCache.java:59)
	at com.ti.ccstudio.debug.service.ApplicationService.getCpuBeingDebugged(ApplicationService.java:1057)
	at com.ti.ccstudio.debug.launch.CCSLaunchDelegate$2.execute(CCSLaunchDelegate.java:139)
	at org.eclipse.cdt.dsf.concurrent.Query.run(Query.java:177)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: org.json.JSONException: Module Closed
	at com.ti.cloudagent.communication.JSONInterface.call(JSONInterface.java:54)
	at com.ti.cloudagent.Agent.createModule(Agent.java:171)
	at com.ti.cloudagent.Agent.lambda$createSpecificModule$4(Agent.java:96)
	at java.util.concurrent.CompletableFuture.uniHandle(Unknown Source)
	at java.util.concurrent.CompletableFuture.uniHandleStage(Unknown Source)
	at java.util.concurrent.CompletableFuture.handle(Unknown Source)
	at com.ti.cloudagent.Agent.createSpecificModule(Agent.java:87)
	at com.ti.cloudagent.Agent.createDeviceDetector(Agent.java:76)
	... 16 more

!ENTRY com.ti.ccstudio.debug 1 0 2019-12-15 21:16:51.697
!MESSAGE DS_ERROR: CS_DAP_0: Error connecting to the target: (Error -261 @ 0x0) Invalid response was received from the XDS110. (Emulation package 8.3.0.00003) 


!ENTRY com.ti.ccstudio.debug 1 0 2019-12-15 21:16:52.039
!MESSAGE DS_ERROR: Error connecting to the target:
(Error -261 @ 0x0)
Invalid response was received from the XDS110.
(Emulation package 8.3.0.00003)


!ENTRY com.ti.ccstudio.debug 1 0 2019-12-15 21:17:14.249
!MESSAGE DS_ERROR: CORTEX_M4_0: JTAG Communication Error: (Error -261 @ 0x0) Invalid response was received from the XDS110. (Emulation package 8.3.0.00003) 


!ENTRY com.ti.ccstudio.debug 1 0 2019-12-15 21:17:14.289
!MESSAGE DS_ERROR: CORTEX_M4_0: Failed to remove the debug state from the target before disconnecting.  There may still be breakpoint op-codes embedded in program memory.  It is recommended that you reset the emulator before you connect and reload your program before you continue debugging


!ENTRY com.ti.ccstudio.debug 4 0 2019-12-15 21:21:21.838
!MESSAGE An internal error was logged by 'com.ti.ccstudio.debug'.
!STACK 0
java.util.concurrent.ExecutionException: org.json.JSONException: Module Closed
	at java.util.concurrent.CompletableFuture.reportGet(Unknown Source)
	at java.util.concurrent.CompletableFuture.get(Unknown Source)
	at com.ti.ccstudio.debug.service.ApplicationService.getConnectedDebugProbes(ApplicationService.java:295)
	at com.ti.ccstudio.debug.service.ApplicationService.detectXDS110ConnectedProbes(ApplicationService.java:356)
	at com.ti.ccstudio.debug.service.ApplicationService.initDebugger(ApplicationService.java:418)
	at com.ti.ccstudio.debug.service.ApplicationService.access$0(ApplicationService.java:408)
	at com.ti.ccstudio.debug.service.ApplicationService$ThreadContextCache.retrieve(ApplicationService.java:136)
	at com.ti.ccstudio.debug.dsf.extensions.concurrent.DataCache.wait(DataCache.java:59)
	at com.ti.ccstudio.debug.service.ApplicationService.getCpuBeingDebugged(ApplicationService.java:1057)
	at com.ti.ccstudio.debug.launch.CCSLaunchDelegate$2.execute(CCSLaunchDelegate.java:139)
	at org.eclipse.cdt.dsf.concurrent.Query.run(Query.java:177)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: org.json.JSONException: Module Closed
	at com.ti.cloudagent.communication.JSONInterface.call(JSONInterface.java:54)
	at com.ti.cloudagent.Agent.createModule(Agent.java:171)
	at com.ti.cloudagent.Agent.lambda$createSpecificModule$4(Agent.java:96)
	at java.util.concurrent.CompletableFuture.uniHandle(Unknown Source)
	at java.util.concurrent.CompletableFuture.uniHandleStage(Unknown Source)
	at java.util.concurrent.CompletableFuture.handle(Unknown Source)
	at com.ti.cloudagent.Agent.createSpecificModule(Agent.java:87)
	at com.ti.cloudagent.Agent.createDeviceDetector(Agent.java:76)
	... 16 more

!ENTRY com.ti.ccstudio.debug 1 0 2019-12-15 21:21:37.330
!MESSAGE DS_ERROR: CORTEX_M4_0: JTAG Communication Error: (Error -261 @ 0x0) Invalid response was received from the XDS110. (Emulation package 8.3.0.00003) 


!ENTRY com.ti.ccstudio.debug 1 0 2019-12-15 21:21:37.373
!MESSAGE DS_ERROR: CORTEX_M4_0: Failed to remove the debug state from the target before disconnecting.  There may still be breakpoint op-codes embedded in program memory.  It is recommended that you reset the emulator before you connect and reload your program before you continue debugging


!ENTRY com.ti.ccstudio.debug 4 0 2019-12-15 21:23:13.156
!MESSAGE An internal error was logged by 'com.ti.ccstudio.debug'.
!STACK 0
java.util.concurrent.ExecutionException: org.json.JSONException: Module Closed
	at java.util.concurrent.CompletableFuture.reportGet(Unknown Source)
	at java.util.concurrent.CompletableFuture.get(Unknown Source)
	at com.ti.ccstudio.debug.service.ApplicationService.getConnectedDebugProbes(ApplicationService.java:295)
	at com.ti.ccstudio.debug.service.ApplicationService.detectXDS110ConnectedProbes(ApplicationService.java:356)
	at com.ti.ccstudio.debug.service.ApplicationService.initDebugger(ApplicationService.java:418)
	at com.ti.ccstudio.debug.service.ApplicationService.access$0(ApplicationService.java:408)
	at com.ti.ccstudio.debug.service.ApplicationService$ThreadContextCache.retrieve(ApplicationService.java:136)
	at com.ti.ccstudio.debug.dsf.extensions.concurrent.DataCache.wait(DataCache.java:59)
	at com.ti.ccstudio.debug.service.ApplicationService.getCpuBeingDebugged(ApplicationService.java:1057)
	at com.ti.ccstudio.debug.launch.CCSLaunchDelegate$2.execute(CCSLaunchDelegate.java:139)
	at org.eclipse.cdt.dsf.concurrent.Query.run(Query.java:177)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: org.json.JSONException: Module Closed
	at com.ti.cloudagent.communication.JSONInterface.call(JSONInterface.java:54)
	at com.ti.cloudagent.Agent.createModule(Agent.java:171)
	at com.ti.cloudagent.Agent.lambda$createSpecificModule$4(Agent.java:96)
	at java.util.concurrent.CompletableFuture.uniHandle(Unknown Source)
	at java.util.concurrent.CompletableFuture.uniHandleStage(Unknown Source)
	at java.util.concurrent.CompletableFuture.handle(Unknown Source)
	at com.ti.cloudagent.Agent.createSpecificModule(Agent.java:87)
	at com.ti.cloudagent.Agent.createDeviceDetector(Agent.java:76)
	... 16 more

!ENTRY com.ti.ccstudio.debug 4 0 2019-12-15 21:24:14.868
!MESSAGE An internal error was logged by 'com.ti.ccstudio.debug'.
!STACK 0
java.util.concurrent.ExecutionException: org.json.JSONException: Module Closed
	at java.util.concurrent.CompletableFuture.reportGet(Unknown Source)
	at java.util.concurrent.CompletableFuture.get(Unknown Source)
	at com.ti.ccstudio.debug.service.ApplicationService.getConnectedDebugProbes(ApplicationService.java:295)
	at com.ti.ccstudio.debug.service.ApplicationService.detectXDS110ConnectedProbes(ApplicationService.java:356)
	at com.ti.ccstudio.debug.service.ApplicationService.initDebugger(ApplicationService.java:418)
	at com.ti.ccstudio.debug.service.ApplicationService.access$0(ApplicationService.java:408)
	at com.ti.ccstudio.debug.service.ApplicationService$ThreadContextCache.retrieve(ApplicationService.java:136)
	at com.ti.ccstudio.debug.dsf.extensions.concurrent.DataCache.wait(DataCache.java:59)
	at com.ti.ccstudio.debug.service.ApplicationService.getCpuBeingDebugged(ApplicationService.java:1057)
	at com.ti.ccstudio.debug.launch.CCSLaunchDelegate$2.execute(CCSLaunchDelegate.java:139)
	at org.eclipse.cdt.dsf.concurrent.Query.run(Query.java:177)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: org.json.JSONException: Module Closed
	at com.ti.cloudagent.communication.JSONInterface.call(JSONInterface.java:54)
	at com.ti.cloudagent.Agent.createModule(Agent.java:171)
	at com.ti.cloudagent.Agent.lambda$createSpecificModule$4(Agent.java:96)
	at java.util.concurrent.CompletableFuture.uniHandle(Unknown Source)
	at java.util.concurrent.CompletableFuture.uniHandleStage(Unknown Source)
	at java.util.concurrent.CompletableFuture.handle(Unknown Source)
	at com.ti.cloudagent.Agent.createSpecificModule(Agent.java:87)
	at com.ti.cloudagent.Agent.createDeviceDetector(Agent.java:76)
	... 16 more

!ENTRY com.ti.ccstudio.debug 4 0 2019-12-15 21:24:32.060
!MESSAGE An internal error was logged by 'com.ti.ccstudio.debug'.
!STACK 0
java.util.concurrent.ExecutionException: org.json.JSONException: Module Closed
	at java.util.concurrent.CompletableFuture.reportGet(Unknown Source)
	at java.util.concurrent.CompletableFuture.get(Unknown Source)
	at com.ti.ccstudio.debug.service.ApplicationService.getConnectedDebugProbes(ApplicationService.java:295)
	at com.ti.ccstudio.debug.service.ApplicationService.detectXDS110ConnectedProbes(ApplicationService.java:356)
	at com.ti.ccstudio.debug.service.ApplicationService.initDebugger(ApplicationService.java:418)
	at com.ti.ccstudio.debug.service.ApplicationService.access$0(ApplicationService.java:408)
	at com.ti.ccstudio.debug.service.ApplicationService$ThreadContextCache.retrieve(ApplicationService.java:136)
	at com.ti.ccstudio.debug.dsf.extensions.concurrent.DataCache.wait(DataCache.java:59)
	at com.ti.ccstudio.debug.service.ApplicationService.getCpuBeingDebugged(ApplicationService.java:1057)
	at com.ti.ccstudio.debug.launch.CCSLaunchDelegate$2.execute(CCSLaunchDelegate.java:139)
	at org.eclipse.cdt.dsf.concurrent.Query.run(Query.java:177)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: org.json.JSONException: Module Closed
	at com.ti.cloudagent.communication.JSONInterface.call(JSONInterface.java:54)
	at com.ti.cloudagent.Agent.createModule(Agent.java:171)
	at com.ti.cloudagent.Agent.lambda$createSpecificModule$4(Agent.java:96)
	at java.util.concurrent.CompletableFuture.uniHandle(Unknown Source)
	at java.util.concurrent.CompletableFuture.uniHandleStage(Unknown Source)
	at java.util.concurrent.CompletableFuture.handle(Unknown Source)
	at com.ti.cloudagent.Agent.createSpecificModule(Agent.java:87)
	at com.ti.cloudagent.Agent.createDeviceDetector(Agent.java:76)
	... 16 more

!ENTRY com.ti.ccstudio.debug 4 0 2019-12-15 21:26:43.338
!MESSAGE An internal error was logged by 'com.ti.ccstudio.debug'.
!STACK 0
java.util.concurrent.ExecutionException: org.json.JSONException: Module Closed
	at java.util.concurrent.CompletableFuture.reportGet(Unknown Source)
	at java.util.concurrent.CompletableFuture.get(Unknown Source)
	at com.ti.ccstudio.debug.service.ApplicationService.getConnectedDebugProbes(ApplicationService.java:295)
	at com.ti.ccstudio.debug.service.ApplicationService.detectXDS110ConnectedProbes(ApplicationService.java:356)
	at com.ti.ccstudio.debug.service.ApplicationService.initDebugger(ApplicationService.java:418)
	at com.ti.ccstudio.debug.service.ApplicationService.access$0(ApplicationService.java:408)
	at com.ti.ccstudio.debug.service.ApplicationService$ThreadContextCache.retrieve(ApplicationService.java:136)
	at com.ti.ccstudio.debug.dsf.extensions.concurrent.DataCache.wait(DataCache.java:59)
	at com.ti.ccstudio.debug.service.ApplicationService.getCpuBeingDebugged(ApplicationService.java:1057)
	at com.ti.ccstudio.debug.launch.CCSLaunchDelegate$2.execute(CCSLaunchDelegate.java:139)
	at org.eclipse.cdt.dsf.concurrent.Query.run(Query.java:177)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: org.json.JSONException: Module Closed
	at com.ti.cloudagent.communication.JSONInterface.call(JSONInterface.java:54)
	at com.ti.cloudagent.Agent.createModule(Agent.java:171)
	at com.ti.cloudagent.Agent.lambda$createSpecificModule$4(Agent.java:96)
	at java.util.concurrent.CompletableFuture.uniHandle(Unknown Source)
	at java.util.concurrent.CompletableFuture.uniHandleStage(Unknown Source)
	at java.util.concurrent.CompletableFuture.handle(Unknown Source)
	at com.ti.cloudagent.Agent.createSpecificModule(Agent.java:87)
	at com.ti.cloudagent.Agent.createDeviceDetector(Agent.java:76)
	... 16 more
